//File edited by soys - Shame of you sniper - 14.March.2021
/**
 * @file Core7.c
 * @generated by CPrinter
 * @date Sun Mar 14 10:05:07 CET 2021
 *
 * Code generated for processing element Core7 (ID=7).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const Stabilization_0_DuplicateFra__0;  // Stabilization_0_DuplicateFrame_0 > Stabilization_end_out_DuplicateFrame_out_1 size:= 72720*char defined in Core0
extern char *const FIFO_Head_Stabilization_end___1;  // FIFO_Head_Stabilization_end_out_DuplicateFrame_out_1 > Stabilization_init_in_ComputeBlockMotionVectorss_previousFrame size:= 72720*char defined in Core0
extern uchar *const out_1_1_1__out_1_1__0;  // Stabilization_0_DuplicateFrame_0_out_1_1_1 > Stabilization_end_out_DuplicateFrame_out_1_out_1_1 size:= 72720*uchar defined in Core0
extern char *const Stabilization_0_ComputeBlock__7;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_6 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__14;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_14 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__22;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_22 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__30;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_30 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__38;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_38 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__46;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_46 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__54;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_54 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__62;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_62 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__140;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_6 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__148;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_14 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__73;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_6 size:= 1024*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__81;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_14 size:= 1024*char defined in Core0
extern coord *const blocksCoord_14__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_14 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_14_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_14__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_14 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_14_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_14_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_14_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_14_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_14__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_14_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_14 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__214;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_14 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__156;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_22 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__89;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_22 size:= 1024*char defined in Core0
extern coord *const blocksCoord_22__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_22 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_22_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_22__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_22 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_22_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_22_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_22_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_22_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_22__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_22_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_22 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__222;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_22 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__164;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_30 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__97;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_30 size:= 1024*char defined in Core0
extern coord *const blocksCoord_30__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_30 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_30_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_30__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_30 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_30_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_30_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_30_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_30_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_30__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_30_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_30 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__230;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_30 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__172;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_38 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__105;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_38 size:= 1024*char defined in Core0
extern coord *const blocksCoord_38__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_38 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_38_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_38__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_38 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_38_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_38_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_38_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_38_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_38__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_38_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_38 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__238;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_38 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__180;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_46 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__113;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_46 size:= 1024*char defined in Core0
extern coord *const blocksCoord_46__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_46 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_46_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_46__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_46 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_46_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_46_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_46_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_46_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_46__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_46_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_46 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__246;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_46 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__188;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_54 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__121;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_54 size:= 1024*char defined in Core0
extern coord *const blocksCoord_54__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_54 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_54_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_54__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_54 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_54_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_54_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_54_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_54_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_54__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_54_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_54 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__254;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_54 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern coord *const blocksCoord_6__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_6 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_6_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_6__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_6 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_6_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_6_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_6_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_6_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_6__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_6_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_6 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__206;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_6 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__196;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_62 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__129;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_62 size:= 1024*char defined in Core0
extern coord *const blocksCoord_62__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_62 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_62_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_62__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_62 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_62_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_62_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_62_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_62_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_62__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_62_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_62 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__262;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_62 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_brFilteredMo__1;  // Stabilization_0_brFilteredMotion_0 > Stabilization_end_out_brFilteredMotion_out_1 size:= 8*char defined in Core0
extern char *const FIFO_Head_Stabilization_end___5;  // FIFO_Head_Stabilization_end_out_brFilteredMotion_out_1 > Stabilization_init_in_AccumulateMotion_filteredMotionIn size:= 8*char defined in Core0
extern coordf *const out_1_1_1__out_1_1__4;  // Stabilization_0_brFilteredMotion_0_out_1_1_1 > Stabilization_end_out_brFilteredMotion_out_1_out_1_1 size:= 1*coordf defined in Core0

// Core Global Definitions

void *computationThread_Core7(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		while(lock(7));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		receiveStart(); // Core0 > Core7: Stabilization_0_DuplicateFra__0
		// SyncComGroup = 0
		receiveEnd(0, 7); // Core0 > Core7: Stabilization_0_DuplicateFra__0
		fifoPush(out_1_1_1__out_1_1__0, FIFO_Head_Stabilization_end___1, 72720*sizeof(char), NULL, 0);
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__7
		// SyncComGroup = 1
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__7
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__14
		// SyncComGroup = 1
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__14
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__22
		// SyncComGroup = 1
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__22
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__30
		// SyncComGroup = 1
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__30
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__38
		// SyncComGroup = 1
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__38
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__46
		// SyncComGroup = 1
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__46
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__54
		// SyncComGroup = 1
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__54
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__62
		// SyncComGroup = 1
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__62
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__140
		// SyncComGroup = 1
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__140
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__148
		// SyncComGroup = 1
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__148
		receiveStart(); // Core0 > Core7: Stabilization_0_ComputeBlock__73
		// SyncComGroup = 1
		receiveEnd(0, 7); // Core0 > Core7: Stabilization_0_ComputeBlock__73
		receiveStart(); // Core0 > Core7: Stabilization_0_ComputeBlock__81
		// SyncComGroup = 1
		receiveEnd(0, 7); // Core0 > Core7: Stabilization_0_ComputeBlock__81
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_14__blockCoord__0,blocksData_14__blockData__0,out_14_65__previousFrame__0,vector__vectors_14__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_14
		// SyncComGroup = 2
		sendStart(7, 0); // Core7 > Core0: Stabilization_0_ComputeBlock__214
		sendEnd(); // Core7 > Core0: Stabilization_0_ComputeBlock__214
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__156
		// SyncComGroup = 3
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__156
		receiveStart(); // Core0 > Core7: Stabilization_0_ComputeBlock__89
		// SyncComGroup = 3
		receiveEnd(0, 7); // Core0 > Core7: Stabilization_0_ComputeBlock__89
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_22__blockCoord__0,blocksData_22__blockData__0,out_22_65__previousFrame__0,vector__vectors_22__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_22
		// SyncComGroup = 4
		sendStart(7, 0); // Core7 > Core0: Stabilization_0_ComputeBlock__222
		sendEnd(); // Core7 > Core0: Stabilization_0_ComputeBlock__222
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__164
		// SyncComGroup = 5
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__164
		receiveStart(); // Core0 > Core7: Stabilization_0_ComputeBlock__97
		// SyncComGroup = 5
		receiveEnd(0, 7); // Core0 > Core7: Stabilization_0_ComputeBlock__97
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_30__blockCoord__0,blocksData_30__blockData__0,out_30_65__previousFrame__0,vector__vectors_30__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_30
		// SyncComGroup = 6
		sendStart(7, 0); // Core7 > Core0: Stabilization_0_ComputeBlock__230
		sendEnd(); // Core7 > Core0: Stabilization_0_ComputeBlock__230
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__172
		// SyncComGroup = 7
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__172
		receiveStart(); // Core0 > Core7: Stabilization_0_ComputeBlock__105
		// SyncComGroup = 7
		receiveEnd(0, 7); // Core0 > Core7: Stabilization_0_ComputeBlock__105
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_38__blockCoord__0,blocksData_38__blockData__0,out_38_65__previousFrame__0,vector__vectors_38__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_38
		// SyncComGroup = 8
		sendStart(7, 0); // Core7 > Core0: Stabilization_0_ComputeBlock__238
		sendEnd(); // Core7 > Core0: Stabilization_0_ComputeBlock__238
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__180
		// SyncComGroup = 9
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__180
		receiveStart(); // Core0 > Core7: Stabilization_0_ComputeBlock__113
		// SyncComGroup = 9
		receiveEnd(0, 7); // Core0 > Core7: Stabilization_0_ComputeBlock__113
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_46__blockCoord__0,blocksData_46__blockData__0,out_46_65__previousFrame__0,vector__vectors_46__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_46
		// SyncComGroup = 10
		sendStart(7, 0); // Core7 > Core0: Stabilization_0_ComputeBlock__246
		sendEnd(); // Core7 > Core0: Stabilization_0_ComputeBlock__246
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__188
		// SyncComGroup = 11
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__188
		receiveStart(); // Core0 > Core7: Stabilization_0_ComputeBlock__121
		// SyncComGroup = 11
		receiveEnd(0, 7); // Core0 > Core7: Stabilization_0_ComputeBlock__121
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_54__blockCoord__0,blocksData_54__blockData__0,out_54_65__previousFrame__0,vector__vectors_54__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_54
		// SyncComGroup = 12
		sendStart(7, 0); // Core7 > Core0: Stabilization_0_ComputeBlock__254
		sendEnd(); // Core7 > Core0: Stabilization_0_ComputeBlock__254
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_6__blockCoord__0,blocksData_6__blockData__0,out_6_65__previousFrame__0,vector__vectors_6__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_6
		// SyncComGroup = 13
		sendStart(7, 0); // Core7 > Core0: Stabilization_0_ComputeBlock__206
		sendEnd(); // Core7 > Core0: Stabilization_0_ComputeBlock__206
		receiveStart(); // Core1 > Core7: Stabilization_0_ComputeBlock__196
		// SyncComGroup = 14
		receiveEnd(1, 7); // Core1 > Core7: Stabilization_0_ComputeBlock__196
		receiveStart(); // Core0 > Core7: Stabilization_0_ComputeBlock__129
		// SyncComGroup = 14
		receiveEnd(0, 7); // Core0 > Core7: Stabilization_0_ComputeBlock__129
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_62__blockCoord__0,blocksData_62__blockData__0,out_62_65__previousFrame__0,vector__vectors_62__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_62
		// SyncComGroup = 15
		sendStart(7, 0); // Core7 > Core0: Stabilization_0_ComputeBlock__262
		sendEnd(); // Core7 > Core0: Stabilization_0_ComputeBlock__262
		receiveStart(); // Core0 > Core7: Stabilization_0_brFilteredMo__1
		// SyncComGroup = 16
		receiveEnd(0, 7); // Core0 > Core7: Stabilization_0_brFilteredMo__1
		fifoPush(out_1_1_1__out_1_1__4, FIFO_Head_Stabilization_end___5, 8*sizeof(char), NULL, 0);
	}
	return NULL;
}

