/**
 * @file Core3.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:09:15 CET 2021
 *
 * Code generated for processing element Core3 (ID=3).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__22;  // explode_Split_0_output > Sobel_22 size:= 6688*char defined in Core0
extern uchar *const output_22__input__0;  // explode_Split_0_output_output_22 > Sobel_22_input size:= 6688*uchar defined in Core0
extern uchar *const output__y_22__0;  // Erosion_22_output > implode_display_0_y_y_22 size:= 3168*uchar defined in Core0
extern char *const Erosion_22__implode_display___0;  // Erosion_22 > implode_display_0_y size:= 3168*char defined in Core0
extern uint64_t dumpedTimes[381]; //  size:= 381*uint64_t
extern int nbExec[381]; //  size:= 381*int

// Core Global Definitions
char Core3[10560]; //  size:= 10560*char
char *const Sobel_22__Dilation_22__0 = (char*) (Core3+0);  // Sobel_22 > Dilation_22 size:= 5984*char
char *const Dilation_22__Erosion_22__0 = (char*) (Core3+5984);  // Dilation_22 > Erosion_22 size:= 4576*char
uchar *const output__input__44 = (uchar*) (Core3+0);  // Sobel_22_output > Dilation_22_input size:= 5984*uchar
uchar *const output__input__45 = (uchar*) (Core3+5984);  // Dilation_22_output > Erosion_22_input size:= 4576*uchar
int idx;

void *computationThread_Core3(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(149/*globalID*/,dumpedTimes); // 
		*(nbExec+150) = 0;
		receiveStart(); // Core0 > Core3: explode_Split_0_output__Sobe__22
		dumpTime(150/*globalID*/,dumpedTimes); // 
		*(nbExec+151) = 0;
		receiveEnd(0, 3); // Core0 > Core3: explode_Split_0_output__Sobe__22
		dumpTime(151/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+152); idx++){
			sobel(352/*width*/,19/*height*/,output_22__input__0,output__input__44); // Sobel_22
		}
		dumpTime(152/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+153); idx++){
			dilation(17/*height*/,352/*width*/,2/*window*/,output__input__44,output__input__45); // Dilation_22
		}
		dumpTime(153/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+154); idx++){
			erosion(13/*height*/,352/*width*/,2/*window*/,output__input__45,output__y_22__0); // Erosion_22
		}
		dumpTime(154/*globalID*/,dumpedTimes); // 
		*(nbExec+155) = 0;
		sendStart(3, 0); // Core3 > Core0: Erosion_22__implode_display___0
		dumpTime(155/*globalID*/,dumpedTimes); // 
		*(nbExec+156) = 0;
		sendEnd(); // Core3 > Core0: Erosion_22__implode_display___0
		dumpTime(156/*globalID*/,dumpedTimes); // 
		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

