/**
 * @file Core19.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:09:15 CET 2021
 *
 * Code generated for processing element Core19 (ID=19).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__11;  // explode_Split_0_output > Sobel_11 size:= 6688*char defined in Core0
extern uchar *const output_11__input__0;  // explode_Split_0_output_output_11 > Sobel_11_input size:= 6688*uchar defined in Core0
extern uchar *const output__y_11__0;  // Erosion_11_output > implode_display_0_y_y_11 size:= 3168*uchar defined in Core0
extern char *const Erosion_11__implode_display___0;  // Erosion_11 > implode_display_0_y size:= 3168*char defined in Core0
extern uint64_t dumpedTimes[381]; //  size:= 381*uint64_t
extern int nbExec[381]; //  size:= 381*int

// Core Global Definitions
char Core19[10560]; //  size:= 10560*char
char *const Sobel_11__Dilation_11__0 = (char*) (Core19+0);  // Sobel_11 > Dilation_11 size:= 5984*char
char *const Dilation_11__Erosion_11__0 = (char*) (Core19+5984);  // Dilation_11 > Erosion_11 size:= 4576*char
uchar *const output__input__22 = (uchar*) (Core19+0);  // Sobel_11_output > Dilation_11_input size:= 5984*uchar
uchar *const output__input__23 = (uchar*) (Core19+5984);  // Dilation_11_output > Erosion_11_input size:= 4576*uchar
int idx;

void *computationThread_Core19(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(277/*globalID*/,dumpedTimes); // 
		*(nbExec+278) = 0;
		receiveStart(); // Core0 > Core19: explode_Split_0_output__Sobe__11
		dumpTime(278/*globalID*/,dumpedTimes); // 
		*(nbExec+279) = 0;
		receiveEnd(0, 19); // Core0 > Core19: explode_Split_0_output__Sobe__11
		dumpTime(279/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+280); idx++){
			sobel(352/*width*/,19/*height*/,output_11__input__0,output__input__22); // Sobel_11
		}
		dumpTime(280/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+281); idx++){
			dilation(17/*height*/,352/*width*/,2/*window*/,output__input__22,output__input__23); // Dilation_11
		}
		dumpTime(281/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+282); idx++){
			erosion(13/*height*/,352/*width*/,2/*window*/,output__input__23,output__y_11__0); // Erosion_11
		}
		dumpTime(282/*globalID*/,dumpedTimes); // 
		*(nbExec+283) = 0;
		sendStart(19, 0); // Core19 > Core0: Erosion_11__implode_display___0
		dumpTime(283/*globalID*/,dumpedTimes); // 
		*(nbExec+284) = 0;
		sendEnd(); // Core19 > Core0: Erosion_11__implode_display___0
		dumpTime(284/*globalID*/,dumpedTimes); // 
		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

