/**
 * @file Core12.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:09:15 CET 2021
 *
 * Code generated for processing element Core12 (ID=12).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__4;  // explode_Split_0_output > Sobel_4 size:= 6688*char defined in Core0
extern uchar *const output_4__input__0;  // explode_Split_0_output_output_4 > Sobel_4_input size:= 6688*uchar defined in Core0
extern uchar *const output__y_4__0;  // Erosion_4_output > implode_display_0_y_y_4 size:= 3168*uchar defined in Core0
extern char *const Erosion_4__implode_display_0__0;  // Erosion_4 > implode_display_0_y size:= 3168*char defined in Core0
extern uint64_t dumpedTimes[381]; //  size:= 381*uint64_t
extern int nbExec[381]; //  size:= 381*int

// Core Global Definitions
char Core12[10560]; //  size:= 10560*char
char *const Sobel_4__Dilation_4__0 = (char*) (Core12+0);  // Sobel_4 > Dilation_4 size:= 5984*char
char *const Dilation_4__Erosion_4__0 = (char*) (Core12+5984);  // Dilation_4 > Erosion_4 size:= 4576*char
uchar *const output__input__8 = (uchar*) (Core12+0);  // Sobel_4_output > Dilation_4_input size:= 5984*uchar
uchar *const output__input__9 = (uchar*) (Core12+5984);  // Dilation_4_output > Erosion_4_input size:= 4576*uchar
int idx;

void *computationThread_Core12(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(221/*globalID*/,dumpedTimes); // 
		*(nbExec+222) = 0;
		receiveStart(); // Core0 > Core12: explode_Split_0_output__Sobe__4
		dumpTime(222/*globalID*/,dumpedTimes); // 
		*(nbExec+223) = 0;
		receiveEnd(0, 12); // Core0 > Core12: explode_Split_0_output__Sobe__4
		dumpTime(223/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+224); idx++){
			sobel(352/*width*/,19/*height*/,output_4__input__0,output__input__8); // Sobel_4
		}
		dumpTime(224/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+225); idx++){
			dilation(17/*height*/,352/*width*/,2/*window*/,output__input__8,output__input__9); // Dilation_4
		}
		dumpTime(225/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+226); idx++){
			erosion(13/*height*/,352/*width*/,2/*window*/,output__input__9,output__y_4__0); // Erosion_4
		}
		dumpTime(226/*globalID*/,dumpedTimes); // 
		*(nbExec+227) = 0;
		sendStart(12, 0); // Core12 > Core0: Erosion_4__implode_display_0__0
		dumpTime(227/*globalID*/,dumpedTimes); // 
		*(nbExec+228) = 0;
		sendEnd(); // Core12 > Core0: Erosion_4__implode_display_0__0
		dumpTime(228/*globalID*/,dumpedTimes); // 
		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

