/**
 * @file Core3.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 18:58:55 CET 2021
 *
 * Code generated for processing element Core3 (ID=3).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern uchar *const output_0__input__0;  // explode_Split_0_output_output_0 > Sobel_0_input size:= 28864*uchar defined in Core0
extern uchar *const output_1__input__0;  // explode_Split_0_output_output_1 > Sobel_1_input size:= 28864*uchar defined in Core0
extern uchar *const output_2__input__0;  // explode_Split_0_output_output_2 > Sobel_2_input size:= 28864*uchar defined in Core0
extern uchar *const output_3__input__0;  // explode_Split_0_output_output_3 > Sobel_3_input size:= 28864*uchar defined in Core0
extern char *const explode_Split_0_output__Sobe__0;  // explode_Split_0_output > Sobel_0 size:= 28864*char defined in Core0
extern char *const explode_Split_0_output__Sobe__1;  // explode_Split_0_output > Sobel_1 size:= 28864*char defined in Core0
extern char *const explode_Split_0_output__Sobe__2;  // explode_Split_0_output > Sobel_2 size:= 28864*char defined in Core0
extern uchar *const output__y_3__0;  // Erosion_3_output > implode_display_0_y_y_3 size:= 25344*uchar defined in Core0
extern char *const Erosion_0__implode_display_0__0;  // Erosion_0 > implode_display_0_y size:= 25344*char defined in Core0
extern char *const Erosion_1__implode_display_0__0;  // Erosion_1 > implode_display_0_y size:= 25344*char defined in Core0
extern char *const Erosion_2__implode_display_0__0;  // Erosion_2 > implode_display_0_y size:= 25344*char defined in Core0
extern uchar *const output__y_0__0;  // Erosion_0_output > implode_display_0_y_y_0 size:= 25344*uchar defined in Core0
extern uchar *const output__y_1__0;  // Erosion_1_output > implode_display_0_y_y_1 size:= 25344*uchar defined in Core0
extern uchar *const output__y_2__0;  // Erosion_2_output > implode_display_0_y_y_2 size:= 25344*uchar defined in Core0
extern uchar *const output__y__0;  // implode_display_0_y_output > display_0_y size:= 101376*uchar defined in Core0
extern char *const implode_display_0_y__display__0;  // implode_display_0_y > display_0 size:= 101376*char defined in Core0
extern uint64_t dumpedTimes[53]; //  size:= 53*uint64_t
extern int nbExec[53]; //  size:= 53*int

// Core Global Definitions
char Core3[54912]; //  size:= 54912*char
char *const Sobel_3__Dilation_3__0 = (char*) (Core3+0);  // Sobel_3 > Dilation_3 size:= 28160*char
char *const Dilation_3__Erosion_3__0 = (char*) (Core3+28160);  // Dilation_3 > Erosion_3 size:= 26752*char
uchar *const output__input__2 = (uchar*) (Core3+0);  // Sobel_3_output > Dilation_3_input size:= 28160*uchar
uchar *const output__input__3 = (uchar*) (Core3+28160);  // Dilation_3_output > Erosion_3_input size:= 26752*uchar
int idx;

void *computationThread_Core3(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(31/*globalID*/,dumpedTimes); // 
		*(nbExec+32) = 0;
		receiveStart(); // Core0 > Core3: NULL
		dumpTime(32/*globalID*/,dumpedTimes); // 
		*(nbExec+33) = 0;
		receiveEnd(0, 3); // Core0 > Core3: NULL
		dumpTime(33/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+34); idx++){
			// Fork explode_Split_0_output
			{
			}
		}
		dumpTime(34/*globalID*/,dumpedTimes); // 
		*(nbExec+35) = 0;
		sendStart(3, 0); // Core3 > Core0: explode_Split_0_output__Sobe__0
		dumpTime(35/*globalID*/,dumpedTimes); // 
		*(nbExec+36) = 0;
		sendEnd(); // Core3 > Core0: explode_Split_0_output__Sobe__0
		dumpTime(36/*globalID*/,dumpedTimes); // 
		*(nbExec+37) = 0;
		sendStart(3, 1); // Core3 > Core1: explode_Split_0_output__Sobe__1
		dumpTime(37/*globalID*/,dumpedTimes); // 
		*(nbExec+38) = 0;
		sendEnd(); // Core3 > Core1: explode_Split_0_output__Sobe__1
		dumpTime(38/*globalID*/,dumpedTimes); // 
		*(nbExec+39) = 0;
		sendStart(3, 2); // Core3 > Core2: explode_Split_0_output__Sobe__2
		dumpTime(39/*globalID*/,dumpedTimes); // 
		*(nbExec+40) = 0;
		sendEnd(); // Core3 > Core2: explode_Split_0_output__Sobe__2
		dumpTime(40/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+41); idx++){
			sobel(352/*width*/,82/*height*/,output_3__input__0,output__input__2); // Sobel_3
		}
		dumpTime(41/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+42); idx++){
			dilation(80/*height*/,352/*width*/,2/*window*/,output__input__2,output__input__3); // Dilation_3
		}
		dumpTime(42/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+43); idx++){
			erosion(76/*height*/,352/*width*/,2/*window*/,output__input__3,output__y_3__0); // Erosion_3
		}
		dumpTime(43/*globalID*/,dumpedTimes); // 
		*(nbExec+44) = 0;
		receiveStart(); // Core0 > Core3: Erosion_0__implode_display_0__0
		dumpTime(44/*globalID*/,dumpedTimes); // 
		*(nbExec+45) = 0;
		receiveEnd(0, 3); // Core0 > Core3: Erosion_0__implode_display_0__0
		dumpTime(45/*globalID*/,dumpedTimes); // 
		*(nbExec+46) = 0;
		receiveStart(); // Core1 > Core3: Erosion_1__implode_display_0__0
		dumpTime(46/*globalID*/,dumpedTimes); // 
		*(nbExec+47) = 0;
		receiveEnd(1, 3); // Core1 > Core3: Erosion_1__implode_display_0__0
		dumpTime(47/*globalID*/,dumpedTimes); // 
		*(nbExec+48) = 0;
		receiveStart(); // Core2 > Core3: Erosion_2__implode_display_0__0
		dumpTime(48/*globalID*/,dumpedTimes); // 
		*(nbExec+49) = 0;
		receiveEnd(2, 3); // Core2 > Core3: Erosion_2__implode_display_0__0
		dumpTime(49/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+50); idx++){
			// Join implode_display_0_y
			{
			}
		}
		dumpTime(50/*globalID*/,dumpedTimes); // 
		*(nbExec+51) = 0;
		sendStart(3, 0); // Core3 > Core0: implode_display_0_y__display__0
		dumpTime(51/*globalID*/,dumpedTimes); // 
		*(nbExec+52) = 0;
		sendEnd(); // Core3 > Core0: implode_display_0_y__display__0
		dumpTime(52/*globalID*/,dumpedTimes); // 
		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

