/**
 * @file Core2.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 18:58:55 CET 2021
 *
 * Code generated for processing element Core2 (ID=2).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__2;  // explode_Split_0_output > Sobel_2 size:= 28864*char defined in Core0
extern uchar *const output_2__input__0;  // explode_Split_0_output_output_2 > Sobel_2_input size:= 28864*uchar defined in Core0
extern uchar *const output__y_2__0;  // Erosion_2_output > implode_display_0_y_y_2 size:= 25344*uchar defined in Core0
extern char *const Erosion_2__implode_display_0__0;  // Erosion_2 > implode_display_0_y size:= 25344*char defined in Core0
extern uint64_t dumpedTimes[53]; //  size:= 53*uint64_t
extern int nbExec[53]; //  size:= 53*int

// Core Global Definitions
char Core2[54912]; //  size:= 54912*char
char *const Sobel_2__Dilation_2__0 = (char*) (Core2+0);  // Sobel_2 > Dilation_2 size:= 28160*char
char *const Dilation_2__Erosion_2__0 = (char*) (Core2+28160);  // Dilation_2 > Erosion_2 size:= 26752*char
uchar *const output__input__6 = (uchar*) (Core2+0);  // Sobel_2_output > Dilation_2_input size:= 28160*uchar
uchar *const output__input__7 = (uchar*) (Core2+28160);  // Dilation_2_output > Erosion_2_input size:= 26752*uchar
int idx;

void *computationThread_Core2(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(23/*globalID*/,dumpedTimes); // 
		*(nbExec+24) = 0;
		receiveStart(); // Core3 > Core2: explode_Split_0_output__Sobe__2
		dumpTime(24/*globalID*/,dumpedTimes); // 
		*(nbExec+25) = 0;
		receiveEnd(3, 2); // Core3 > Core2: explode_Split_0_output__Sobe__2
		dumpTime(25/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+26); idx++){
			sobel(352/*width*/,82/*height*/,output_2__input__0,output__input__6); // Sobel_2
		}
		dumpTime(26/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+27); idx++){
			dilation(80/*height*/,352/*width*/,2/*window*/,output__input__6,output__input__7); // Dilation_2
		}
		dumpTime(27/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+28); idx++){
			erosion(76/*height*/,352/*width*/,2/*window*/,output__input__7,output__y_2__0); // Erosion_2
		}
		dumpTime(28/*globalID*/,dumpedTimes); // 
		*(nbExec+29) = 0;
		sendStart(2, 3); // Core2 > Core3: Erosion_2__implode_display_0__0
		dumpTime(29/*globalID*/,dumpedTimes); // 
		*(nbExec+30) = 0;
		sendEnd(); // Core2 > Core3: Erosion_2__implode_display_0__0
		dumpTime(30/*globalID*/,dumpedTimes); // 
		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

