//File edited by soys - Shame of you sniper - 27.March.2021
//File edited by Cowa - CoW automatic script - 27.March.2021
/**
 * @file Core6.c
 * @generated by CPrinter
 * @date Sun Mar 14 10:12:14 CET 2021
 *
 * Code generated for processing element Core6 (ID=6).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
#include "cow_master.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const Stabilization_0_DuplicateFra__0;  // Stabilization_0_DuplicateFrame_0 > Stabilization_end_out_DuplicateFrame_out_1 size:= 72720*char defined in Core0
extern char *const FIFO_Head_Stabilization_end___1;  // FIFO_Head_Stabilization_end_out_DuplicateFrame_out_1 > Stabilization_init_in_ComputeBlockMotionVectorss_previousFrame size:= 72720*char defined in Core0
extern uchar *const out_1_1_1__out_1_1__0;  // Stabilization_0_DuplicateFrame_0_out_1_1_1 > Stabilization_end_out_DuplicateFrame_out_1_out_1_1 size:= 72720*uchar defined in Core0
extern char *const Stabilization_0_ComputeBlock__6;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_5 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__37;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_37 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__139;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_5 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__171;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_37 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__72;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_5 size:= 1024*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__104;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_37 size:= 1024*char defined in Core0
extern coord *const blocksCoord_37__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_37 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_37_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_37__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_37 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_37_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_37_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_37_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_37_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_37__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_37_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_37 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__237;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_37 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern coord *const blocksCoord_5__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_5 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_5_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_5__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_5 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_5_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_5_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_5_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_5_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_5__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_5_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_5 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__205;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_5 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_brFilteredMo__1;  // Stabilization_0_brFilteredMotion_0 > Stabilization_end_out_brFilteredMotion_out_1 size:= 8*char defined in Core0
extern char *const FIFO_Head_Stabilization_end___5;  // FIFO_Head_Stabilization_end_out_brFilteredMotion_out_1 > Stabilization_init_in_AccumulateMotion_filteredMotionIn size:= 8*char defined in Core0
extern coordf *const out_1_1_1__out_1_1__4;  // Stabilization_0_brFilteredMotion_0_out_1_1_1 > Stabilization_end_out_brFilteredMotion_out_1_out_1_1 size:= 1*coordf defined in Core0

// Core Global Definitions

void *computationThread_Core6(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		reconfigure_CoW(index);
		while(lock(6));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		receiveStart(); // Core0 > Core6: Stabilization_0_DuplicateFra__0
		// SyncComGroup = 0
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_DuplicateFra__0
		fifoPush(out_1_1_1__out_1_1__0, FIFO_Head_Stabilization_end___1, 72720*sizeof(char), NULL, 0);
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__6
		// SyncComGroup = 1
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__6
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__37
		// SyncComGroup = 1
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__37
		receiveStart(); // Core0 > Core6: Stabilization_0_ComputeBlock__139
		// SyncComGroup = 1
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_ComputeBlock__139
		receiveStart(); // Core0 > Core6: Stabilization_0_ComputeBlock__171
		// SyncComGroup = 1
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_ComputeBlock__171
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__72
		// SyncComGroup = 1
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__72
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__104
		// SyncComGroup = 1
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__104
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_37__blockCoord__0,blocksData_37__blockData__0,out_37_65__previousFrame__0,vector__vectors_37__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_37
		// SyncComGroup = 2
		sendStart(6, 0); // Core6 > Core0: Stabilization_0_ComputeBlock__237
		sendEnd(); // Core6 > Core0: Stabilization_0_ComputeBlock__237
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_5__blockCoord__0,blocksData_5__blockData__0,out_5_65__previousFrame__0,vector__vectors_5__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_5
		// SyncComGroup = 3
		sendStart(6, 0); // Core6 > Core0: Stabilization_0_ComputeBlock__205
		sendEnd(); // Core6 > Core0: Stabilization_0_ComputeBlock__205
		receiveStart(); // Core0 > Core6: Stabilization_0_brFilteredMo__1
		// SyncComGroup = 4
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_brFilteredMo__1
		fifoPush(out_1_1_1__out_1_1__4, FIFO_Head_Stabilization_end___5, 8*sizeof(char), NULL, 0);
	}
	return NULL;
}

