//File edited by soys - Shame of you sniper - 27.March.2021
/**
 * @file Core18.c
 * @generated by CPrinter
 * @date Sun Mar 14 10:12:14 CET 2021
 *
 * Code generated for processing element Core18 (ID=18).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
#include "ntm.h"
#include <emmintrin.h>
#include <smmintrin.h>
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const Stabilization_0_ComputeBlock__17;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_17 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__151;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_17 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__49;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_49 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__84;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_17 size:= 1024*char defined in Core0
extern coord *const blocksCoord_17__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_17 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_17_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_17__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_17 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_17_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_17_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_17_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_17_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_17__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_17_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_17 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__217;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_17 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__183;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_49 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__116;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_49 size:= 1024*char defined in Core0
extern coord *const blocksCoord_49__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_49 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_49_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_49__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_49 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_49_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_49_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_49_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_49_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_49__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_49_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_49 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__249;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_49 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0

// Core Global Definitions

void *computationThread_Core18(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		while(lock(18));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		receiveStart(); // Core1 > Core18: Stabilization_0_ComputeBlock__17
		// SyncComGroup = 0
		receiveEnd(1, 18); // Core1 > Core18: Stabilization_0_ComputeBlock__17
		receiveStart(); // Core0 > Core18: Stabilization_0_ComputeBlock__151
		// SyncComGroup = 0
		receiveEnd(0, 18); // Core0 > Core18: Stabilization_0_ComputeBlock__151
		receiveStart(); // Core1 > Core18: Stabilization_0_ComputeBlock__49
		// SyncComGroup = 0
		receiveEnd(1, 18); // Core1 > Core18: Stabilization_0_ComputeBlock__49
		receiveStart(); // Core1 > Core18: Stabilization_0_ComputeBlock__84
		// SyncComGroup = 0
		receiveEnd(1, 18); // Core1 > Core18: Stabilization_0_ComputeBlock__84
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_17__blockCoord__0,blocksData_17__blockData__0,out_17_65__previousFrame__0,vector__vectors_17__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_17
		// SyncComGroup = 1
		sendStart(18, 0); // Core18 > Core0: Stabilization_0_ComputeBlock__217
		sendEnd(); // Core18 > Core0: Stabilization_0_ComputeBlock__217
		receiveStart(); // Core0 > Core18: Stabilization_0_ComputeBlock__183
		// SyncComGroup = 2
		receiveEnd(0, 18); // Core0 > Core18: Stabilization_0_ComputeBlock__183
		receiveStart(); // Core1 > Core18: Stabilization_0_ComputeBlock__116
		// SyncComGroup = 2
		receiveEnd(1, 18); // Core1 > Core18: Stabilization_0_ComputeBlock__116
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_49__blockCoord__0,blocksData_49__blockData__0,out_49_65__previousFrame__0,vector__vectors_49__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_49
		// SyncComGroup = 3
		sendStart(18, 0); // Core18 > Core0: Stabilization_0_ComputeBlock__249
		sendEnd(); // Core18 > Core0: Stabilization_0_ComputeBlock__249
	}
	return NULL;
}

