/**
 * @file Core28.c
 * @generated by CPrinter
 * @date Sun Mar 14 10:12:14 CET 2021
 *
 * Code generated for processing element Core28 (ID=28).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const Stabilization_0_ComputeBlock__26;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_26 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__160;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_26 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__58;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_58 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__93;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_26 size:= 1024*char defined in Core0
extern coord *const blocksCoord_26__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_26 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_26_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_26__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_26 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_26_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_26_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_26_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_26_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_26__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_26_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_26 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__226;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_26 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__192;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_58 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__125;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_58 size:= 1024*char defined in Core0
extern coord *const blocksCoord_58__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_58 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_58_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_58__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_58 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_58_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_58_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_58_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_58_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_58__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_58_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_58 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__258;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_58 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0

// Core Global Definitions

void *computationThread_Core28(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		receiveStart(); // Core1 > Core28: Stabilization_0_ComputeBlock__26
		// SyncComGroup = 0
		receiveEnd(1, 28); // Core1 > Core28: Stabilization_0_ComputeBlock__26
		receiveStart(); // Core0 > Core28: Stabilization_0_ComputeBlock__160
		// SyncComGroup = 0
		receiveEnd(0, 28); // Core0 > Core28: Stabilization_0_ComputeBlock__160
		receiveStart(); // Core1 > Core28: Stabilization_0_ComputeBlock__58
		// SyncComGroup = 0
		receiveEnd(1, 28); // Core1 > Core28: Stabilization_0_ComputeBlock__58
		receiveStart(); // Core1 > Core28: Stabilization_0_ComputeBlock__93
		// SyncComGroup = 0
		receiveEnd(1, 28); // Core1 > Core28: Stabilization_0_ComputeBlock__93
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_26__blockCoord__0,blocksData_26__blockData__0,out_26_65__previousFrame__0,vector__vectors_26__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_26
		// SyncComGroup = 1
		sendStart(28, 0); // Core28 > Core0: Stabilization_0_ComputeBlock__226
		sendEnd(); // Core28 > Core0: Stabilization_0_ComputeBlock__226
		receiveStart(); // Core0 > Core28: Stabilization_0_ComputeBlock__192
		// SyncComGroup = 2
		receiveEnd(0, 28); // Core0 > Core28: Stabilization_0_ComputeBlock__192
		receiveStart(); // Core1 > Core28: Stabilization_0_ComputeBlock__125
		// SyncComGroup = 2
		receiveEnd(1, 28); // Core1 > Core28: Stabilization_0_ComputeBlock__125
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_58__blockCoord__0,blocksData_58__blockData__0,out_58_65__previousFrame__0,vector__vectors_58__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_58
		// SyncComGroup = 3
		sendStart(28, 0); // Core28 > Core0: Stabilization_0_ComputeBlock__258
		sendEnd(); // Core28 > Core0: Stabilization_0_ComputeBlock__258
	}
	return NULL;
}

