/**
 * @file Core6.c
 * @generated by CPrinter
 * @date Sun Mar 14 10:00:51 CET 2021
 *
 * Code generated for processing element Core6 (ID=6).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const Stabilization_0_ComputeBlock__8;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_7 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__15;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_15 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__23;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_23 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__31;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_31 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__39;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_39 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__47;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_47 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__55;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_55 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__63;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_63 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__141;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_7 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__149;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_15 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__74;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_7 size:= 1024*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__82;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_15 size:= 1024*char defined in Core0
extern coord *const blocksCoord_15__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_15 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_15_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_15__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_15 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_15_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_15_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_15_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_15_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_15__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_15_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_15 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__215;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_15 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__157;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_23 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__90;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_23 size:= 1024*char defined in Core0
extern coord *const blocksCoord_23__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_23 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_23_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_23__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_23 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_23_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_23_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_23_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_23_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_23__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_23_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_23 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__223;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_23 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__165;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_31 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__98;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_31 size:= 1024*char defined in Core0
extern coord *const blocksCoord_31__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_31 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_31_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_31__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_31 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_31_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_31_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_31_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_31_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_31__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_31_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_31 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__231;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_31 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__173;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_39 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__106;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_39 size:= 1024*char defined in Core0
extern coord *const blocksCoord_39__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_39 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_39_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_39__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_39 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_39_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_39_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_39_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_39_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_39__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_39_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_39 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__239;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_39 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__181;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_47 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__114;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_47 size:= 1024*char defined in Core0
extern coord *const blocksCoord_47__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_47 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_47_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_47__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_47 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_47_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_47_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_47_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_47_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_47__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_47_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_47 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__247;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_47 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__189;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_55 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__122;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_55 size:= 1024*char defined in Core0
extern coord *const blocksCoord_55__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_55 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_55_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_55__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_55 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_55_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_55_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_55_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_55_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_55__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_55_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_55 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__255;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_55 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__197;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_63 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__130;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_63 size:= 1024*char defined in Core0
extern coord *const blocksCoord_63__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_63 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_63_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_63__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_63 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_63_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_63_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_63_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_63_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_63__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_63_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_63 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__263;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_63 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern coord *const blocksCoord_7__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_7 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_7_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_7__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_7 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_7_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_7_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_7_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_7_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_7__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_7_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_7 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__207;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_7 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_DuplicateAcc__1;  // Stabilization_0_DuplicateAccumulatedMotion_0 > Stabilization_end_out_DuplicateAccumulatedMotion_out_1 size:= 8*char defined in Core0
extern char *const FIFO_Head_Stabilization_end___4;  // FIFO_Head_Stabilization_end_out_DuplicateAccumulatedMotion_out_1 > Stabilization_init_in_AccumulateMotion_accumulatedMotionIn size:= 8*char defined in Core0
extern coordf *const out_1_1_1__out_1_1__3;  // Stabilization_0_DuplicateAccumulatedMotion_0_out_1_1_1 > Stabilization_end_out_DuplicateAccumulatedMotion_out_1_out_1_1 size:= 1*coordf defined in Core0

// Core Global Definitions

void *computationThread_Core6(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__8
		// SyncComGroup = 0
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__8
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__15
		// SyncComGroup = 0
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__15
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__23
		// SyncComGroup = 0
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__23
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__31
		// SyncComGroup = 0
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__31
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__39
		// SyncComGroup = 0
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__39
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__47
		// SyncComGroup = 0
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__47
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__55
		// SyncComGroup = 0
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__55
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__63
		// SyncComGroup = 0
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__63
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__141
		// SyncComGroup = 0
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__141
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__149
		// SyncComGroup = 0
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__149
		receiveStart(); // Core0 > Core6: Stabilization_0_ComputeBlock__74
		// SyncComGroup = 0
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_ComputeBlock__74
		receiveStart(); // Core0 > Core6: Stabilization_0_ComputeBlock__82
		// SyncComGroup = 0
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_ComputeBlock__82
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_15__blockCoord__0,blocksData_15__blockData__0,out_15_65__previousFrame__0,vector__vectors_15__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_15
		// SyncComGroup = 1
		sendStart(6, 0); // Core6 > Core0: Stabilization_0_ComputeBlock__215
		sendEnd(); // Core6 > Core0: Stabilization_0_ComputeBlock__215
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__157
		// SyncComGroup = 2
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__157
		receiveStart(); // Core0 > Core6: Stabilization_0_ComputeBlock__90
		// SyncComGroup = 2
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_ComputeBlock__90
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_23__blockCoord__0,blocksData_23__blockData__0,out_23_65__previousFrame__0,vector__vectors_23__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_23
		// SyncComGroup = 3
		sendStart(6, 0); // Core6 > Core0: Stabilization_0_ComputeBlock__223
		sendEnd(); // Core6 > Core0: Stabilization_0_ComputeBlock__223
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__165
		// SyncComGroup = 4
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__165
		receiveStart(); // Core0 > Core6: Stabilization_0_ComputeBlock__98
		// SyncComGroup = 4
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_ComputeBlock__98
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_31__blockCoord__0,blocksData_31__blockData__0,out_31_65__previousFrame__0,vector__vectors_31__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_31
		// SyncComGroup = 5
		sendStart(6, 0); // Core6 > Core0: Stabilization_0_ComputeBlock__231
		sendEnd(); // Core6 > Core0: Stabilization_0_ComputeBlock__231
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__173
		// SyncComGroup = 6
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__173
		receiveStart(); // Core0 > Core6: Stabilization_0_ComputeBlock__106
		// SyncComGroup = 6
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_ComputeBlock__106
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_39__blockCoord__0,blocksData_39__blockData__0,out_39_65__previousFrame__0,vector__vectors_39__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_39
		// SyncComGroup = 7
		sendStart(6, 0); // Core6 > Core0: Stabilization_0_ComputeBlock__239
		sendEnd(); // Core6 > Core0: Stabilization_0_ComputeBlock__239
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__181
		// SyncComGroup = 8
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__181
		receiveStart(); // Core0 > Core6: Stabilization_0_ComputeBlock__114
		// SyncComGroup = 8
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_ComputeBlock__114
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_47__blockCoord__0,blocksData_47__blockData__0,out_47_65__previousFrame__0,vector__vectors_47__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_47
		// SyncComGroup = 9
		sendStart(6, 0); // Core6 > Core0: Stabilization_0_ComputeBlock__247
		sendEnd(); // Core6 > Core0: Stabilization_0_ComputeBlock__247
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__189
		// SyncComGroup = 10
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__189
		receiveStart(); // Core0 > Core6: Stabilization_0_ComputeBlock__122
		// SyncComGroup = 10
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_ComputeBlock__122
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_55__blockCoord__0,blocksData_55__blockData__0,out_55_65__previousFrame__0,vector__vectors_55__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_55
		// SyncComGroup = 11
		sendStart(6, 0); // Core6 > Core0: Stabilization_0_ComputeBlock__255
		sendEnd(); // Core6 > Core0: Stabilization_0_ComputeBlock__255
		receiveStart(); // Core1 > Core6: Stabilization_0_ComputeBlock__197
		// SyncComGroup = 12
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_ComputeBlock__197
		receiveStart(); // Core0 > Core6: Stabilization_0_ComputeBlock__130
		// SyncComGroup = 12
		receiveEnd(0, 6); // Core0 > Core6: Stabilization_0_ComputeBlock__130
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_63__blockCoord__0,blocksData_63__blockData__0,out_63_65__previousFrame__0,vector__vectors_63__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_63
		// SyncComGroup = 13
		sendStart(6, 0); // Core6 > Core0: Stabilization_0_ComputeBlock__263
		sendEnd(); // Core6 > Core0: Stabilization_0_ComputeBlock__263
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_7__blockCoord__0,blocksData_7__blockData__0,out_7_65__previousFrame__0,vector__vectors_7__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_7
		// SyncComGroup = 14
		sendStart(6, 0); // Core6 > Core0: Stabilization_0_ComputeBlock__207
		sendEnd(); // Core6 > Core0: Stabilization_0_ComputeBlock__207
		receiveStart(); // Core1 > Core6: Stabilization_0_DuplicateAcc__1
		// SyncComGroup = 15
		receiveEnd(1, 6); // Core1 > Core6: Stabilization_0_DuplicateAcc__1
		fifoPush(out_1_1_1__out_1_1__3, FIFO_Head_Stabilization_end___4, 8*sizeof(char), NULL, 0);
	}
	return NULL;
}

