//File edited by soys - Shame of you sniper - 18.March.2021
/**
 * @file Core31.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:09:15 CET 2021
 *
 * Code generated for processing element Core31 (ID=31).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__24;  // explode_Split_0_output > Sobel_24 size:= 6688*char defined in Core0
extern uchar *const output_24__input__0;  // explode_Split_0_output_output_24 > Sobel_24_input size:= 6688*uchar defined in Core0
extern uchar *const output__y_24__0;  // Erosion_24_output > implode_display_0_y_y_24 size:= 3168*uchar defined in Core0
extern char *const Erosion_24__implode_display___0;  // Erosion_24 > implode_display_0_y size:= 3168*char defined in Core0
extern uint64_t dumpedTimes[381]; //  size:= 381*uint64_t
extern int nbExec[381]; //  size:= 381*int

// Core Global Definitions
char Core31[10560]; //  size:= 10560*char
char *const Sobel_24__Dilation_24__0 = (char*) (Core31+0);  // Sobel_24 > Dilation_24 size:= 5984*char
char *const Dilation_24__Erosion_24__0 = (char*) (Core31+5984);  // Dilation_24 > Erosion_24 size:= 4576*char
uchar *const output__input__48 = (uchar*) (Core31+0);  // Sobel_24_output > Dilation_24_input size:= 5984*uchar
uchar *const output__input__49 = (uchar*) (Core31+5984);  // Dilation_24_output > Erosion_24_input size:= 4576*uchar
int idx;

void *computationThread_Core31(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		while(lock(31));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(373/*globalID*/,dumpedTimes); // 
		*(nbExec+374) = 0;
		receiveStart(); // Core0 > Core31: explode_Split_0_output__Sobe__24
		dumpTime(374/*globalID*/,dumpedTimes); // 
		*(nbExec+375) = 0;
		receiveEnd(0, 31); // Core0 > Core31: explode_Split_0_output__Sobe__24
		dumpTime(375/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+376); idx++){
			sobel(352/*width*/,19/*height*/,output_24__input__0,output__input__48); // Sobel_24
		}
		dumpTime(376/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+377); idx++){
			dilation(17/*height*/,352/*width*/,2/*window*/,output__input__48,output__input__49); // Dilation_24
		}
		dumpTime(377/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+378); idx++){
			erosion(13/*height*/,352/*width*/,2/*window*/,output__input__49,output__y_24__0); // Erosion_24
		}
		dumpTime(378/*globalID*/,dumpedTimes); // 
		*(nbExec+379) = 0;
		sendStart(31, 0); // Core31 > Core0: Erosion_24__implode_display___0
		dumpTime(379/*globalID*/,dumpedTimes); // 
		*(nbExec+380) = 0;
		sendEnd(); // Core31 > Core0: Erosion_24__implode_display___0
		dumpTime(380/*globalID*/,dumpedTimes); // 
		while(lock(31));
//		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

