//File edited by soys - Shame of you sniper - 18.March.2021
/**
 * @file Core29.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:09:15 CET 2021
 *
 * Code generated for processing element Core29 (ID=29).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__21;  // explode_Split_0_output > Sobel_21 size:= 6688*char defined in Core0
extern uchar *const output_21__input__0;  // explode_Split_0_output_output_21 > Sobel_21_input size:= 6688*uchar defined in Core0
extern uchar *const output__y_21__0;  // Erosion_21_output > implode_display_0_y_y_21 size:= 3168*uchar defined in Core0
extern char *const Erosion_21__implode_display___0;  // Erosion_21 > implode_display_0_y size:= 3168*char defined in Core0
extern uint64_t dumpedTimes[381]; //  size:= 381*uint64_t
extern int nbExec[381]; //  size:= 381*int

// Core Global Definitions
char Core29[10560]; //  size:= 10560*char
char *const Sobel_21__Dilation_21__0 = (char*) (Core29+0);  // Sobel_21 > Dilation_21 size:= 5984*char
char *const Dilation_21__Erosion_21__0 = (char*) (Core29+5984);  // Dilation_21 > Erosion_21 size:= 4576*char
uchar *const output__input__42 = (uchar*) (Core29+0);  // Sobel_21_output > Dilation_21_input size:= 5984*uchar
uchar *const output__input__43 = (uchar*) (Core29+5984);  // Dilation_21_output > Erosion_21_input size:= 4576*uchar
int idx;

void *computationThread_Core29(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		while(lock(29));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(357/*globalID*/,dumpedTimes); // 
		*(nbExec+358) = 0;
		receiveStart(); // Core0 > Core29: explode_Split_0_output__Sobe__21
		dumpTime(358/*globalID*/,dumpedTimes); // 
		*(nbExec+359) = 0;
		receiveEnd(0, 29); // Core0 > Core29: explode_Split_0_output__Sobe__21
		dumpTime(359/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+360); idx++){
			sobel(352/*width*/,19/*height*/,output_21__input__0,output__input__42); // Sobel_21
		}
		dumpTime(360/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+361); idx++){
			dilation(17/*height*/,352/*width*/,2/*window*/,output__input__42,output__input__43); // Dilation_21
		}
		dumpTime(361/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+362); idx++){
			erosion(13/*height*/,352/*width*/,2/*window*/,output__input__43,output__y_21__0); // Erosion_21
		}
		dumpTime(362/*globalID*/,dumpedTimes); // 
		*(nbExec+363) = 0;
		sendStart(29, 0); // Core29 > Core0: Erosion_21__implode_display___0
		dumpTime(363/*globalID*/,dumpedTimes); // 
		*(nbExec+364) = 0;
		sendEnd(); // Core29 > Core0: Erosion_21__implode_display___0
		dumpTime(364/*globalID*/,dumpedTimes); // 
		while(lock(29));
//		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

