//File edited by soys - Shame of you sniper - 18.March.2021
/**
 * @file Core22.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:09:15 CET 2021
 *
 * Code generated for processing element Core22 (ID=22).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__15;  // explode_Split_0_output > Sobel_15 size:= 6688*char defined in Core0
extern uchar *const output_15__input__0;  // explode_Split_0_output_output_15 > Sobel_15_input size:= 6688*uchar defined in Core0
extern uchar *const output__y_15__0;  // Erosion_15_output > implode_display_0_y_y_15 size:= 3168*uchar defined in Core0
extern char *const Erosion_15__implode_display___0;  // Erosion_15 > implode_display_0_y size:= 3168*char defined in Core0
extern uint64_t dumpedTimes[381]; //  size:= 381*uint64_t
extern int nbExec[381]; //  size:= 381*int

// Core Global Definitions
char Core22[10560]; //  size:= 10560*char
char *const Sobel_15__Dilation_15__0 = (char*) (Core22+0);  // Sobel_15 > Dilation_15 size:= 5984*char
char *const Dilation_15__Erosion_15__0 = (char*) (Core22+5984);  // Dilation_15 > Erosion_15 size:= 4576*char
uchar *const output__input__30 = (uchar*) (Core22+0);  // Sobel_15_output > Dilation_15_input size:= 5984*uchar
uchar *const output__input__31 = (uchar*) (Core22+5984);  // Dilation_15_output > Erosion_15_input size:= 4576*uchar
int idx;

void *computationThread_Core22(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		while(lock(22));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(301/*globalID*/,dumpedTimes); // 
		*(nbExec+302) = 0;
		receiveStart(); // Core0 > Core22: explode_Split_0_output__Sobe__15
		dumpTime(302/*globalID*/,dumpedTimes); // 
		*(nbExec+303) = 0;
		receiveEnd(0, 22); // Core0 > Core22: explode_Split_0_output__Sobe__15
		dumpTime(303/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+304); idx++){
			sobel(352/*width*/,19/*height*/,output_15__input__0,output__input__30); // Sobel_15
		}
		dumpTime(304/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+305); idx++){
			dilation(17/*height*/,352/*width*/,2/*window*/,output__input__30,output__input__31); // Dilation_15
		}
		dumpTime(305/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+306); idx++){
			erosion(13/*height*/,352/*width*/,2/*window*/,output__input__31,output__y_15__0); // Erosion_15
		}
		dumpTime(306/*globalID*/,dumpedTimes); // 
		*(nbExec+307) = 0;
		sendStart(22, 0); // Core22 > Core0: Erosion_15__implode_display___0
		dumpTime(307/*globalID*/,dumpedTimes); // 
		*(nbExec+308) = 0;
		sendEnd(); // Core22 > Core0: Erosion_15__implode_display___0
		dumpTime(308/*globalID*/,dumpedTimes); // 
		while(lock(22));
//		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

