//File edited by soys - Shame of you sniper - 18.March.2021
/**
 * @file Core26.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:09:15 CET 2021
 *
 * Code generated for processing element Core26 (ID=26).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__31;  // explode_Split_0_output > Sobel_31 size:= 6688*char defined in Core0
extern uchar *const output_31__input__0;  // explode_Split_0_output_output_31 > Sobel_31_input size:= 6688*uchar defined in Core0
extern uchar *const output__y_31__0;  // Erosion_31_output > implode_display_0_y_y_31 size:= 3168*uchar defined in Core0
extern char *const Erosion_31__implode_display___0;  // Erosion_31 > implode_display_0_y size:= 3168*char defined in Core0
extern uint64_t dumpedTimes[381]; //  size:= 381*uint64_t
extern int nbExec[381]; //  size:= 381*int

// Core Global Definitions
char Core26[10560]; //  size:= 10560*char
char *const Sobel_31__Dilation_31__0 = (char*) (Core26+0);  // Sobel_31 > Dilation_31 size:= 5984*char
char *const Dilation_31__Erosion_31__0 = (char*) (Core26+5984);  // Dilation_31 > Erosion_31 size:= 4576*char
uchar *const output__input__62 = (uchar*) (Core26+0);  // Sobel_31_output > Dilation_31_input size:= 5984*uchar
uchar *const output__input__63 = (uchar*) (Core26+5984);  // Dilation_31_output > Erosion_31_input size:= 4576*uchar
int idx;

void *computationThread_Core26(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		while(lock(26));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(333/*globalID*/,dumpedTimes); // 
		*(nbExec+334) = 0;
		receiveStart(); // Core0 > Core26: explode_Split_0_output__Sobe__31
		dumpTime(334/*globalID*/,dumpedTimes); // 
		*(nbExec+335) = 0;
		receiveEnd(0, 26); // Core0 > Core26: explode_Split_0_output__Sobe__31
		dumpTime(335/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+336); idx++){
			sobel(352/*width*/,19/*height*/,output_31__input__0,output__input__62); // Sobel_31
		}
		dumpTime(336/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+337); idx++){
			dilation(17/*height*/,352/*width*/,2/*window*/,output__input__62,output__input__63); // Dilation_31
		}
		dumpTime(337/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+338); idx++){
			erosion(13/*height*/,352/*width*/,2/*window*/,output__input__63,output__y_31__0); // Erosion_31
		}
		dumpTime(338/*globalID*/,dumpedTimes); // 
		*(nbExec+339) = 0;
		sendStart(26, 0); // Core26 > Core0: Erosion_31__implode_display___0
		dumpTime(339/*globalID*/,dumpedTimes); // 
		*(nbExec+340) = 0;
		sendEnd(); // Core26 > Core0: Erosion_31__implode_display___0
		dumpTime(340/*globalID*/,dumpedTimes); // 
		while(lock(26));
//		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

