//File edited by soys - Shame of you sniper - 19.March.2021
/**
 * @file Core12.c
 * @generated by CPrinter
 * @date Sun Mar 14 10:06:25 CET 2021
 *
 * Code generated for processing element Core12 (ID=12).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const Stabilization_0_ComputeBlock__12;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__146;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__28;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__44;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__60;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__79;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12 size:= 1024*char defined in Core0
extern coord *const blocksCoord_12__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_12 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_12__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_12 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_12_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_12_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_12__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_12 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__212;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__162;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__95;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28 size:= 1024*char defined in Core0
extern coord *const blocksCoord_28__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_28 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_28__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_28 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_28_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_28_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_28__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_28 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__228;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__178;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__111;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44 size:= 1024*char defined in Core0
extern coord *const blocksCoord_44__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_44 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_44__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_44 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_44_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_44_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_44__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_44 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__244;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__194;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__127;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60 size:= 1024*char defined in Core0
extern coord *const blocksCoord_60__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_60 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_60__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_60 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_60_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_60_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_60__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_60 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__260;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0

// Core Global Definitions

void *computationThread_Core12(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		while(lock(12));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		receiveStart(); // Core1 > Core12: Stabilization_0_ComputeBlock__12
		// SyncComGroup = 0
		receiveEnd(1, 12); // Core1 > Core12: Stabilization_0_ComputeBlock__12
		receiveStart(); // Core0 > Core12: Stabilization_0_ComputeBlock__146
		// SyncComGroup = 0
		receiveEnd(0, 12); // Core0 > Core12: Stabilization_0_ComputeBlock__146
		receiveStart(); // Core1 > Core12: Stabilization_0_ComputeBlock__28
		// SyncComGroup = 0
		receiveEnd(1, 12); // Core1 > Core12: Stabilization_0_ComputeBlock__28
		receiveStart(); // Core1 > Core12: Stabilization_0_ComputeBlock__44
		// SyncComGroup = 0
		receiveEnd(1, 12); // Core1 > Core12: Stabilization_0_ComputeBlock__44
		receiveStart(); // Core1 > Core12: Stabilization_0_ComputeBlock__60
		// SyncComGroup = 0
		receiveEnd(1, 12); // Core1 > Core12: Stabilization_0_ComputeBlock__60
		receiveStart(); // Core1 > Core12: Stabilization_0_ComputeBlock__79
		// SyncComGroup = 0
		receiveEnd(1, 12); // Core1 > Core12: Stabilization_0_ComputeBlock__79
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_12__blockCoord__0,blocksData_12__blockData__0,out_12_65__previousFrame__0,vector__vectors_12__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12
		// SyncComGroup = 1
		sendStart(12, 0); // Core12 > Core0: Stabilization_0_ComputeBlock__212
		sendEnd(); // Core12 > Core0: Stabilization_0_ComputeBlock__212
		receiveStart(); // Core0 > Core12: Stabilization_0_ComputeBlock__162
		// SyncComGroup = 2
		receiveEnd(0, 12); // Core0 > Core12: Stabilization_0_ComputeBlock__162
		receiveStart(); // Core1 > Core12: Stabilization_0_ComputeBlock__95
		// SyncComGroup = 2
		receiveEnd(1, 12); // Core1 > Core12: Stabilization_0_ComputeBlock__95
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_28__blockCoord__0,blocksData_28__blockData__0,out_28_65__previousFrame__0,vector__vectors_28__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28
		// SyncComGroup = 3
		sendStart(12, 0); // Core12 > Core0: Stabilization_0_ComputeBlock__228
		sendEnd(); // Core12 > Core0: Stabilization_0_ComputeBlock__228
		receiveStart(); // Core0 > Core12: Stabilization_0_ComputeBlock__178
		// SyncComGroup = 4
		receiveEnd(0, 12); // Core0 > Core12: Stabilization_0_ComputeBlock__178
		receiveStart(); // Core1 > Core12: Stabilization_0_ComputeBlock__111
		// SyncComGroup = 4
		receiveEnd(1, 12); // Core1 > Core12: Stabilization_0_ComputeBlock__111
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_44__blockCoord__0,blocksData_44__blockData__0,out_44_65__previousFrame__0,vector__vectors_44__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44
		// SyncComGroup = 5
		sendStart(12, 0); // Core12 > Core0: Stabilization_0_ComputeBlock__244
		sendEnd(); // Core12 > Core0: Stabilization_0_ComputeBlock__244
		receiveStart(); // Core0 > Core12: Stabilization_0_ComputeBlock__194
		// SyncComGroup = 6
		receiveEnd(0, 12); // Core0 > Core12: Stabilization_0_ComputeBlock__194
		receiveStart(); // Core1 > Core12: Stabilization_0_ComputeBlock__127
		// SyncComGroup = 6
		receiveEnd(1, 12); // Core1 > Core12: Stabilization_0_ComputeBlock__127
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_60__blockCoord__0,blocksData_60__blockData__0,out_60_65__previousFrame__0,vector__vectors_60__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60
		// SyncComGroup = 7
		sendStart(12, 0); // Core12 > Core0: Stabilization_0_ComputeBlock__260
		sendEnd(); // Core12 > Core0: Stabilization_0_ComputeBlock__260
	}
	return NULL;
}

