//File edited by soys - Shame of you sniper - 19.March.2021
/**
 * @file Core3.c
 * @generated by CPrinter
 * @date Sun Mar 14 10:06:25 CET 2021
 *
 * Code generated for processing element Core3 (ID=3).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const Stabilization_0_ComputeBlock__4;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__19;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__137;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__153;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__35;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__51;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__70;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3 size:= 1024*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__86;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19 size:= 1024*char defined in Core0
extern coord *const blocksCoord_19__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_19 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_19__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_19 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_19_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_19_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_19__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_19 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__219;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern coord *const blocksCoord_3__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_3 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_3__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_3 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_3_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_3_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_3__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_3 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__203;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__169;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__102;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35 size:= 1024*char defined in Core0
extern coord *const blocksCoord_35__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_35 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_35__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_35 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_35_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_35_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_35__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_35 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__235;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__185;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__118;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51 size:= 1024*char defined in Core0
extern coord *const blocksCoord_51__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_51 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_51__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_51 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_51_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_51_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_51__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_51 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__251;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_BrY_0__Dupli__0;  // Stabilization_0_BrY_0 > DuplicateY_0 size:= 225120*char defined in Core0
extern uchar *const out_0_0__y__0;  // DuplicateY_0_out_0_0 > DisplayYUV_0_y size:= 225120*uchar defined in Core0
extern uchar *const out_1_1__y__0;  // DuplicateY_0_out_1_1 > WriteYUV_0_y size:= 225120*uchar defined in Core0
extern uchar *const out_0_0__in__0;  // Stabilization_0_BrY_0_out_0_0 > DuplicateY_0_in size:= 225120*uchar defined in Core0
extern char *const DuplicateY_0__DisplayYUV_0__0;  // DuplicateY_0 > DisplayYUV_0 size:= 225120*char defined in Core0
extern char *const DuplicateY_0__WriteYUV_0__0;  // DuplicateY_0 > WriteYUV_0 size:= 225120*char defined in Core0

// Core Global Definitions

void *computationThread_Core3(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		while(lock(3));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__4
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__4
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__19
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__19
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__137
		// SyncComGroup = 0
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__137
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__153
		// SyncComGroup = 0
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__153
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__35
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__35
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__51
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__51
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__70
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__70
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__86
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__86
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_19__blockCoord__0,blocksData_19__blockData__0,out_19_65__previousFrame__0,vector__vectors_19__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19
		// SyncComGroup = 1
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__219
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__219
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_3__blockCoord__0,blocksData_3__blockData__0,out_3_65__previousFrame__0,vector__vectors_3__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3
		// SyncComGroup = 2
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__203
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__203
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__169
		// SyncComGroup = 3
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__169
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__102
		// SyncComGroup = 3
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__102
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_35__blockCoord__0,blocksData_35__blockData__0,out_35_65__previousFrame__0,vector__vectors_35__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35
		// SyncComGroup = 4
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__235
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__235
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__185
		// SyncComGroup = 5
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__185
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__118
		// SyncComGroup = 5
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__118
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_51__blockCoord__0,blocksData_51__blockData__0,out_51_65__previousFrame__0,vector__vectors_51__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51
		// SyncComGroup = 6
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__251
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__251
		receiveStart(); // Core0 > Core3: Stabilization_0_BrY_0__Dupli__0
		// SyncComGroup = 7
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_BrY_0__Dupli__0
		// Broadcast DuplicateY_0
		{
			// memcpy #0
			// memcpy #0
		}
		// SyncComGroup = 8
		sendStart(3, 0); // Core3 > Core0: DuplicateY_0__DisplayYUV_0__0
		sendEnd(); // Core3 > Core0: DuplicateY_0__DisplayYUV_0__0
		// SyncComGroup = 8
		sendStart(3, 1); // Core3 > Core1: DuplicateY_0__WriteYUV_0__0
		sendEnd(); // Core3 > Core1: DuplicateY_0__WriteYUV_0__0
	}
	return NULL;
}

