/**
 * @file Core4.c
 * @generated by CPrinter
 * @date Tue Mar 23 20:04:42 CET 2021
 *
 * Code generated for processing element Core4 (ID=4).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const Stabilization_0_ComputeBlock__5;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_4 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__12;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__20;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_20 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__28;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__36;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_36 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__44;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__52;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_52 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__60;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__138;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_4 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__146;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__71;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_4 size:= 1024*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__79;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12 size:= 1024*char defined in Core0
extern coord *const blocksCoord_12__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_12 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_12__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_12 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_12_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_12_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_12__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_12 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__212;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__154;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_20 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__87;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_20 size:= 1024*char defined in Core0
extern coord *const blocksCoord_20__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_20 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_20_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_20__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_20 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_20_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_20_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_20_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_20_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_20__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_20_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_20 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__220;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_20 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__162;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__95;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28 size:= 1024*char defined in Core0
extern coord *const blocksCoord_28__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_28 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_28__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_28 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_28_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_28_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_28__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_28 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__228;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__170;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_36 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__103;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_36 size:= 1024*char defined in Core0
extern coord *const blocksCoord_36__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_36 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_36_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_36__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_36 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_36_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_36_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_36_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_36_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_36__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_36_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_36 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__236;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_36 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern coord *const blocksCoord_4__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_4 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_4_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_4__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_4 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_4_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_4_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_4_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_4_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_4__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_4_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_4 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__204;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_4 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__178;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__111;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44 size:= 1024*char defined in Core0
extern coord *const blocksCoord_44__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_44 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_44__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_44 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_44_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_44_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_44__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_44 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__244;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__186;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_52 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__119;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_52 size:= 1024*char defined in Core0
extern coord *const blocksCoord_52__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_52 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_52_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_52__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_52 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_52_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_52_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_52_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_52_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_52__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_52_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_52 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__252;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_52 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__194;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__127;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60 size:= 1024*char defined in Core0
extern coord *const blocksCoord_60__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_60 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_60__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_60 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_60_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_60_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_60__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_60 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__260;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_BrU_0__Stabi__0;  // Stabilization_0_BrU_0 > Stabilization_end_out_BrU_out_1 size:= 56280*char defined in Core0
extern char *const FIFO_Head_Stabilization_end___2;  // FIFO_Head_Stabilization_end_out_BrU_out_1 > Stabilization_init_in_renderFrame_uPrev size:= 56280*char defined in Core0
extern uchar *const out_1_1_1__out_1_1__1;  // Stabilization_0_BrU_0_out_1_1_1 > Stabilization_end_out_BrU_out_1_out_1_1 size:= 56280*uchar defined in Core0

// Core Global Definitions

void *computationThread_Core4(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__5
		// SyncComGroup = 0
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__5
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__12
		// SyncComGroup = 0
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__12
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__20
		// SyncComGroup = 0
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__20
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__28
		// SyncComGroup = 0
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__28
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__36
		// SyncComGroup = 0
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__36
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__44
		// SyncComGroup = 0
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__44
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__52
		// SyncComGroup = 0
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__52
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__60
		// SyncComGroup = 0
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__60
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__138
		// SyncComGroup = 0
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__138
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__146
		// SyncComGroup = 0
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__146
		receiveStart(); // Core0 > Core4: Stabilization_0_ComputeBlock__71
		// SyncComGroup = 0
		receiveEnd(0, 4); // Core0 > Core4: Stabilization_0_ComputeBlock__71
		receiveStart(); // Core0 > Core4: Stabilization_0_ComputeBlock__79
		// SyncComGroup = 0
		receiveEnd(0, 4); // Core0 > Core4: Stabilization_0_ComputeBlock__79
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_12__blockCoord__0,blocksData_12__blockData__0,out_12_65__previousFrame__0,vector__vectors_12__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_12
		// SyncComGroup = 1
		sendStart(4, 0); // Core4 > Core0: Stabilization_0_ComputeBlock__212
		sendEnd(); // Core4 > Core0: Stabilization_0_ComputeBlock__212
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__154
		// SyncComGroup = 2
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__154
		receiveStart(); // Core0 > Core4: Stabilization_0_ComputeBlock__87
		// SyncComGroup = 2
		receiveEnd(0, 4); // Core0 > Core4: Stabilization_0_ComputeBlock__87
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_20__blockCoord__0,blocksData_20__blockData__0,out_20_65__previousFrame__0,vector__vectors_20__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_20
		// SyncComGroup = 3
		sendStart(4, 0); // Core4 > Core0: Stabilization_0_ComputeBlock__220
		sendEnd(); // Core4 > Core0: Stabilization_0_ComputeBlock__220
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__162
		// SyncComGroup = 4
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__162
		receiveStart(); // Core0 > Core4: Stabilization_0_ComputeBlock__95
		// SyncComGroup = 4
		receiveEnd(0, 4); // Core0 > Core4: Stabilization_0_ComputeBlock__95
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_28__blockCoord__0,blocksData_28__blockData__0,out_28_65__previousFrame__0,vector__vectors_28__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_28
		// SyncComGroup = 5
		sendStart(4, 0); // Core4 > Core0: Stabilization_0_ComputeBlock__228
		sendEnd(); // Core4 > Core0: Stabilization_0_ComputeBlock__228
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__170
		// SyncComGroup = 6
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__170
		receiveStart(); // Core0 > Core4: Stabilization_0_ComputeBlock__103
		// SyncComGroup = 6
		receiveEnd(0, 4); // Core0 > Core4: Stabilization_0_ComputeBlock__103
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_36__blockCoord__0,blocksData_36__blockData__0,out_36_65__previousFrame__0,vector__vectors_36__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_36
		// SyncComGroup = 7
		sendStart(4, 0); // Core4 > Core0: Stabilization_0_ComputeBlock__236
		sendEnd(); // Core4 > Core0: Stabilization_0_ComputeBlock__236
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_4__blockCoord__0,blocksData_4__blockData__0,out_4_65__previousFrame__0,vector__vectors_4__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_4
		// SyncComGroup = 8
		sendStart(4, 0); // Core4 > Core0: Stabilization_0_ComputeBlock__204
		sendEnd(); // Core4 > Core0: Stabilization_0_ComputeBlock__204
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__178
		// SyncComGroup = 9
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__178
		receiveStart(); // Core0 > Core4: Stabilization_0_ComputeBlock__111
		// SyncComGroup = 9
		receiveEnd(0, 4); // Core0 > Core4: Stabilization_0_ComputeBlock__111
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_44__blockCoord__0,blocksData_44__blockData__0,out_44_65__previousFrame__0,vector__vectors_44__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_44
		// SyncComGroup = 10
		sendStart(4, 0); // Core4 > Core0: Stabilization_0_ComputeBlock__244
		sendEnd(); // Core4 > Core0: Stabilization_0_ComputeBlock__244
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__186
		// SyncComGroup = 11
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__186
		receiveStart(); // Core0 > Core4: Stabilization_0_ComputeBlock__119
		// SyncComGroup = 11
		receiveEnd(0, 4); // Core0 > Core4: Stabilization_0_ComputeBlock__119
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_52__blockCoord__0,blocksData_52__blockData__0,out_52_65__previousFrame__0,vector__vectors_52__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_52
		// SyncComGroup = 12
		sendStart(4, 0); // Core4 > Core0: Stabilization_0_ComputeBlock__252
		sendEnd(); // Core4 > Core0: Stabilization_0_ComputeBlock__252
		receiveStart(); // Core1 > Core4: Stabilization_0_ComputeBlock__194
		// SyncComGroup = 13
		receiveEnd(1, 4); // Core1 > Core4: Stabilization_0_ComputeBlock__194
		receiveStart(); // Core0 > Core4: Stabilization_0_ComputeBlock__127
		// SyncComGroup = 13
		receiveEnd(0, 4); // Core0 > Core4: Stabilization_0_ComputeBlock__127
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_60__blockCoord__0,blocksData_60__blockData__0,out_60_65__previousFrame__0,vector__vectors_60__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_60
		// SyncComGroup = 14
		sendStart(4, 0); // Core4 > Core0: Stabilization_0_ComputeBlock__260
		sendEnd(); // Core4 > Core0: Stabilization_0_ComputeBlock__260
		receiveStart(); // Core2 > Core4: Stabilization_0_BrU_0__Stabi__0
		// SyncComGroup = 15
		receiveEnd(2, 4); // Core2 > Core4: Stabilization_0_BrU_0__Stabi__0
		fifoPush(out_1_1_1__out_1_1__1, FIFO_Head_Stabilization_end___2, 56280*sizeof(char), NULL, 0);
	}
	return NULL;
}

