/**
 * @file Core3.c
 * @generated by CPrinter
 * @date Tue Mar 23 20:04:42 CET 2021
 *
 * Code generated for processing element Core3 (ID=3).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const Stabilization_0_ComputeBlock__4;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__11;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_11 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__19;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__27;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_27 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__35;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__43;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_43 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__51;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__59;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_59 size:= 72720*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__137;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__145;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_11 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__70;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3 size:= 1024*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__78;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_11 size:= 1024*char defined in Core0
extern coord *const blocksCoord_11__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_11 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_11_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_11__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_11 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_11_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_11_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_11_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_11_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_11__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_11_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_11 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__211;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_11 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__153;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__86;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19 size:= 1024*char defined in Core0
extern coord *const blocksCoord_19__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_19 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_19__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_19 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_19_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_19_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_19__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_19 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__219;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__161;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_27 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__94;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_27 size:= 1024*char defined in Core0
extern coord *const blocksCoord_27__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_27 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_27_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_27__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_27 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_27_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_27_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_27_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_27_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_27__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_27_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_27 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__227;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_27 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern coord *const blocksCoord_3__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_3 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_3__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_3 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_3_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_3_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_3__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_3 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__203;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__169;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__102;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35 size:= 1024*char defined in Core0
extern coord *const blocksCoord_35__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_35 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_35__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_35 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_35_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_35_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_35__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_35 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__235;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__177;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_43 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__110;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_43 size:= 1024*char defined in Core0
extern coord *const blocksCoord_43__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_43 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_43_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_43__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_43 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_43_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_43_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_43_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_43_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_43__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_43_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_43 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__243;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_43 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__185;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__118;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51 size:= 1024*char defined in Core0
extern coord *const blocksCoord_51__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_51 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_51__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_51 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_51_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_51_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_51__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_51 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__251;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__193;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_59 size:= 8*char defined in Core0
extern char *const Stabilization_0_ComputeBlock__126;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_59 size:= 1024*char defined in Core0
extern coord *const blocksCoord_59__blockCoord__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksCoord_blocksCoord_59 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_59_blockCoord size:= 1*coord defined in Core0
extern uchar *const blocksData_59__blockData__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_explode_Stabilization_0_ComputeBlockMotionVectorss_0_DivideBlocks_0_blocksData_blocksData_59 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_59_blockData size:= 1024*uchar defined in Core0
extern uchar *const out_59_65__previousFrame__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_DuplicatePreviousFrame_0_out_59_65 > Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_59_previousFrame size:= 72720*uchar defined in Core0
extern coord *const vector__vectors_59__0;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_59_vector > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors_vectors_59 size:= 1*coord defined in Core0
extern char *const Stabilization_0_ComputeBlock__259;  // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_59 > Stabilization_0_implode_Stabilization_0_FindDominatingMotion_0_vectors size:= 8*char defined in Core0
extern char *const Stabilization_0_renderFrame___2;  // Stabilization_0_renderFrame_0 > Stabilization_0_BrV_0 size:= 56280*char defined in Core0
extern uchar *const out_1_1_1__out_1_1__2;  // Stabilization_0_BrV_0_out_1_1_1 > Stabilization_end_out_BrV_out_1_out_1_1 size:= 56280*uchar defined in Core0
extern uchar *const out_0_0__in__2;  // Stabilization_0_BrV_0_out_0_0 > DuplicateV_0_in size:= 56280*uchar defined in Core0
extern uchar *const vOut__in__0;  // Stabilization_0_renderFrame_0_vOut > Stabilization_0_BrV_0_in size:= 56280*uchar defined in Core0
extern char *const Stabilization_0_BrV_0__Stabi__0;  // Stabilization_0_BrV_0 > Stabilization_end_out_BrV_out_1 size:= 56280*char defined in Core0
extern uchar *const out_0_0__v__0;  // DuplicateV_0_out_0_0 > DisplayYUV_0_v size:= 56280*uchar defined in Core0
extern uchar *const out_1_1__v__0;  // DuplicateV_0_out_1_1 > WriteYUV_0_v size:= 56280*uchar defined in Core0
extern char *const DuplicateV_0__DisplayYUV_0__0;  // DuplicateV_0 > DisplayYUV_0 size:= 56280*char defined in Core0
extern char *const DuplicateV_0__WriteYUV_0__0;  // DuplicateV_0 > WriteYUV_0 size:= 56280*char defined in Core0

// Core Global Definitions

void *computationThread_Core3(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__4
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__4
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__11
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__11
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__19
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__19
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__27
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__27
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__35
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__35
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__43
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__43
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__51
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__51
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__59
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__59
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__137
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__137
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__145
		// SyncComGroup = 0
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__145
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__70
		// SyncComGroup = 0
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__70
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__78
		// SyncComGroup = 0
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__78
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_11__blockCoord__0,blocksData_11__blockData__0,out_11_65__previousFrame__0,vector__vectors_11__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_11
		// SyncComGroup = 1
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__211
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__211
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__153
		// SyncComGroup = 2
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__153
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__86
		// SyncComGroup = 2
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__86
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_19__blockCoord__0,blocksData_19__blockData__0,out_19_65__previousFrame__0,vector__vectors_19__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_19
		// SyncComGroup = 3
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__219
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__219
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__161
		// SyncComGroup = 4
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__161
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__94
		// SyncComGroup = 4
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__94
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_27__blockCoord__0,blocksData_27__blockData__0,out_27_65__previousFrame__0,vector__vectors_27__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_27
		// SyncComGroup = 5
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__227
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__227
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_3__blockCoord__0,blocksData_3__blockData__0,out_3_65__previousFrame__0,vector__vectors_3__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_3
		// SyncComGroup = 6
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__203
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__203
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__169
		// SyncComGroup = 7
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__169
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__102
		// SyncComGroup = 7
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__102
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_35__blockCoord__0,blocksData_35__blockData__0,out_35_65__previousFrame__0,vector__vectors_35__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_35
		// SyncComGroup = 8
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__235
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__235
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__177
		// SyncComGroup = 9
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__177
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__110
		// SyncComGroup = 9
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__110
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_43__blockCoord__0,blocksData_43__blockData__0,out_43_65__previousFrame__0,vector__vectors_43__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_43
		// SyncComGroup = 10
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__243
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__243
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__185
		// SyncComGroup = 11
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__185
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__118
		// SyncComGroup = 11
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__118
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_51__blockCoord__0,blocksData_51__blockData__0,out_51_65__previousFrame__0,vector__vectors_51__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_51
		// SyncComGroup = 12
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__251
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__251
		receiveStart(); // Core1 > Core3: Stabilization_0_ComputeBlock__193
		// SyncComGroup = 13
		receiveEnd(1, 3); // Core1 > Core3: Stabilization_0_ComputeBlock__193
		receiveStart(); // Core0 > Core3: Stabilization_0_ComputeBlock__126
		// SyncComGroup = 13
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_ComputeBlock__126
		computeBlockMotionVector(360/*width*/,202/*height*/,32/*blockWidth*/,32/*blockHeight*/,38/*maxDeltaX*/,21/*maxDeltaY*/,blocksCoord_59__blockCoord__0,blocksData_59__blockData__0,out_59_65__previousFrame__0,vector__vectors_59__0); // Stabilization_0_ComputeBlockMotionVectorss_0_ComputeBlockMotionVector_59
		// SyncComGroup = 14
		sendStart(3, 0); // Core3 > Core0: Stabilization_0_ComputeBlock__259
		sendEnd(); // Core3 > Core0: Stabilization_0_ComputeBlock__259
		receiveStart(); // Core0 > Core3: Stabilization_0_renderFrame___2
		// SyncComGroup = 15
		receiveEnd(0, 3); // Core0 > Core3: Stabilization_0_renderFrame___2
		// Broadcast Stabilization_0_BrV_0
		{
			// memcpy #0
			memcpy(out_1_1_1__out_1_1__2+0, vOut__in__0+0, 56280*sizeof(uchar));
			// memcpy #0
		}
		// SyncComGroup = 16
		sendStart(3, 5); // Core3 > Core5: Stabilization_0_BrV_0__Stabi__0
		sendEnd(); // Core3 > Core5: Stabilization_0_BrV_0__Stabi__0
		// Broadcast DuplicateV_0
		{
			// memcpy #0
			// memcpy #0
		}
		// SyncComGroup = 17
		sendStart(3, 0); // Core3 > Core0: DuplicateV_0__DisplayYUV_0__0
		sendEnd(); // Core3 > Core0: DuplicateV_0__DisplayYUV_0__0
		// SyncComGroup = 17
		sendStart(3, 1); // Core3 > Core1: DuplicateV_0__WriteYUV_0__0
		sendEnd(); // Core3 > Core1: DuplicateV_0__WriteYUV_0__0
	}
	return NULL;
}

