//File edited by soys - Shame of you sniper - 18.March.2021
/**
 * @file Core12.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:00:00 CET 2021
 *
 * Code generated for processing element Core12 (ID=12).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__4;  // explode_Split_0_output > Sobel_4 size:= 9856*char defined in Core0
extern uchar *const output_4__input__0;  // explode_Split_0_output_output_4 > Sobel_4_input size:= 9856*uchar defined in Core0
extern uchar *const output__y_4__0;  // Erosion_4_output > implode_display_0_y_y_4 size:= 6336*uchar defined in Core0
extern char *const Erosion_4__implode_display_0__0;  // Erosion_4 > implode_display_0_y size:= 6336*char defined in Core0
extern uint64_t dumpedTimes[189]; //  size:= 189*uint64_t
extern int nbExec[189]; //  size:= 189*int

// Core Global Definitions
char Core12[16896]; //  size:= 16896*char
char *const Sobel_4__Dilation_4__0 = (char*) (Core12+0);  // Sobel_4 > Dilation_4 size:= 9152*char
char *const Dilation_4__Erosion_4__0 = (char*) (Core12+9152);  // Dilation_4 > Erosion_4 size:= 7744*char
uchar *const output__input__8 = (uchar*) (Core12+0);  // Sobel_4_output > Dilation_4_input size:= 9152*uchar
uchar *const output__input__9 = (uchar*) (Core12+9152);  // Dilation_4_output > Erosion_4_input size:= 7744*uchar
int idx;

void *computationThread_Core12(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		while(lock(12));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(157/*globalID*/,dumpedTimes); // 
		*(nbExec+158) = 0;
		receiveStart(); // Core0 > Core12: explode_Split_0_output__Sobe__4
		dumpTime(158/*globalID*/,dumpedTimes); // 
		*(nbExec+159) = 0;
		receiveEnd(0, 12); // Core0 > Core12: explode_Split_0_output__Sobe__4
		dumpTime(159/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+160); idx++){
			sobel(352/*width*/,28/*height*/,output_4__input__0,output__input__8); // Sobel_4
		}
		dumpTime(160/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+161); idx++){
			dilation(26/*height*/,352/*width*/,2/*window*/,output__input__8,output__input__9); // Dilation_4
		}
		dumpTime(161/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+162); idx++){
			erosion(22/*height*/,352/*width*/,2/*window*/,output__input__9,output__y_4__0); // Erosion_4
		}
		dumpTime(162/*globalID*/,dumpedTimes); // 
		*(nbExec+163) = 0;
		sendStart(12, 0); // Core12 > Core0: Erosion_4__implode_display_0__0
		dumpTime(163/*globalID*/,dumpedTimes); // 
		*(nbExec+164) = 0;
		sendEnd(); // Core12 > Core0: Erosion_4__implode_display_0__0
		dumpTime(164/*globalID*/,dumpedTimes); // 
		while(lock(12));
//		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

