//File edited by soys - Shame of you sniper - 18.March.2021
/**
 * @file Core10.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:00:00 CET 2021
 *
 * Code generated for processing element Core10 (ID=10).
 */

#include "preesm_gen.h"
#include "path_sniper.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__2;  // explode_Split_0_output > Sobel_2 size:= 9856*char defined in Core0
extern uchar *const output_2__input__0;  // explode_Split_0_output_output_2 > Sobel_2_input size:= 9856*uchar defined in Core0
extern uchar *const output__y_2__0;  // Erosion_2_output > implode_display_0_y_y_2 size:= 6336*uchar defined in Core0
extern char *const Erosion_2__implode_display_0__0;  // Erosion_2 > implode_display_0_y size:= 6336*char defined in Core0
extern uint64_t dumpedTimes[189]; //  size:= 189*uint64_t
extern int nbExec[189]; //  size:= 189*int

// Core Global Definitions
char Core10[16896]; //  size:= 16896*char
char *const Sobel_2__Dilation_2__0 = (char*) (Core10+0);  // Sobel_2 > Dilation_2 size:= 9152*char
char *const Dilation_2__Erosion_2__0 = (char*) (Core10+9152);  // Dilation_2 > Erosion_2 size:= 7744*char
uchar *const output__input__4 = (uchar*) (Core10+0);  // Sobel_2_output > Dilation_2_input size:= 9152*uchar
uchar *const output__input__5 = (uchar*) (Core10+9152);  // Dilation_2_output > Erosion_2_input size:= 7744*uchar
int idx;

void *computationThread_Core10(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		while(lock(10));
//		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(141/*globalID*/,dumpedTimes); // 
		*(nbExec+142) = 0;
		receiveStart(); // Core0 > Core10: explode_Split_0_output__Sobe__2
		dumpTime(142/*globalID*/,dumpedTimes); // 
		*(nbExec+143) = 0;
		receiveEnd(0, 10); // Core0 > Core10: explode_Split_0_output__Sobe__2
		dumpTime(143/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+144); idx++){
			sobel(352/*width*/,28/*height*/,output_2__input__0,output__input__4); // Sobel_2
		}
		dumpTime(144/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+145); idx++){
			dilation(26/*height*/,352/*width*/,2/*window*/,output__input__4,output__input__5); // Dilation_2
		}
		dumpTime(145/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+146); idx++){
			erosion(22/*height*/,352/*width*/,2/*window*/,output__input__5,output__y_2__0); // Erosion_2
		}
		dumpTime(146/*globalID*/,dumpedTimes); // 
		*(nbExec+147) = 0;
		sendStart(10, 0); // Core10 > Core0: Erosion_2__implode_display_0__0
		dumpTime(147/*globalID*/,dumpedTimes); // 
		*(nbExec+148) = 0;
		sendEnd(); // Core10 > Core0: Erosion_2__implode_display_0__0
		dumpTime(148/*globalID*/,dumpedTimes); // 
		while(lock(10));
//		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

