/**
 * @file Core8.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:00:00 CET 2021
 *
 * Code generated for processing element Core8 (ID=8).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__14;  // explode_Split_0_output > Sobel_14 size:= 9856*char defined in Core0
extern uchar *const output_14__input__0;  // explode_Split_0_output_output_14 > Sobel_14_input size:= 9856*uchar defined in Core0
extern uchar *const output__y_14__0;  // Erosion_14_output > implode_display_0_y_y_14 size:= 6336*uchar defined in Core0
extern char *const Erosion_14__implode_display___0;  // Erosion_14 > implode_display_0_y size:= 6336*char defined in Core0
extern uint64_t dumpedTimes[189]; //  size:= 189*uint64_t
extern int nbExec[189]; //  size:= 189*int

// Core Global Definitions
char Core8[16896]; //  size:= 16896*char
char *const Sobel_14__Dilation_14__0 = (char*) (Core8+0);  // Sobel_14 > Dilation_14 size:= 9152*char
char *const Dilation_14__Erosion_14__0 = (char*) (Core8+9152);  // Dilation_14 > Erosion_14 size:= 7744*char
uchar *const output__input__28 = (uchar*) (Core8+0);  // Sobel_14_output > Dilation_14_input size:= 9152*uchar
uchar *const output__input__29 = (uchar*) (Core8+9152);  // Dilation_14_output > Erosion_14_input size:= 7744*uchar
int idx;

void *computationThread_Core8(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(125/*globalID*/,dumpedTimes); // 
		*(nbExec+126) = 0;
		receiveStart(); // Core0 > Core8: explode_Split_0_output__Sobe__14
		dumpTime(126/*globalID*/,dumpedTimes); // 
		*(nbExec+127) = 0;
		receiveEnd(0, 8); // Core0 > Core8: explode_Split_0_output__Sobe__14
		dumpTime(127/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+128); idx++){
			sobel(352/*width*/,28/*height*/,output_14__input__0,output__input__28); // Sobel_14
		}
		dumpTime(128/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+129); idx++){
			dilation(26/*height*/,352/*width*/,2/*window*/,output__input__28,output__input__29); // Dilation_14
		}
		dumpTime(129/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+130); idx++){
			erosion(22/*height*/,352/*width*/,2/*window*/,output__input__29,output__y_14__0); // Erosion_14
		}
		dumpTime(130/*globalID*/,dumpedTimes); // 
		*(nbExec+131) = 0;
		sendStart(8, 0); // Core8 > Core0: Erosion_14__implode_display___0
		dumpTime(131/*globalID*/,dumpedTimes); // 
		*(nbExec+132) = 0;
		sendEnd(); // Core8 > Core0: Erosion_14__implode_display___0
		dumpTime(132/*globalID*/,dumpedTimes); // 
		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

