/**
 * @file Core0.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:00:00 CET 2021
 *
 * Code generated for processing element Core0 (ID=0).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;

// Core Global Definitions
char Core0[67584]; //  size:= 67584*char
char Shared[206272]; //  size:= 206272*char
char *const Read_YUV_0__display_0__0 = (char*) (Core0+0);  // Read_YUV_0 > display_0 size:= 50688*char
char *const Sobel_0__Dilation_0__0 = (char*) (Core0+50688);  // Sobel_0 > Dilation_0 size:= 9152*char
char *const Dilation_0__Erosion_0__0 = (char*) (Core0+59840);  // Dilation_0 > Erosion_0 size:= 7744*char
char *const Read_YUV_0__Split_0__0 = (char*) (Shared+1760);  // Read_YUV_0 > Split_0 size:= 101376*char
char *const explode_Split_0_output__Sobe__0 = (char*) (Shared+0);  // explode_Split_0_output > Sobel_0 size:= 9856*char
char *const explode_Split_0_output__Sobe__1 = (char*) (Shared+6336);  // explode_Split_0_output > Sobel_1 size:= 9856*char
char *const explode_Split_0_output__Sobe__2 = (char*) (Shared+12672);  // explode_Split_0_output > Sobel_2 size:= 9856*char
char *const explode_Split_0_output__Sobe__3 = (char*) (Shared+19008);  // explode_Split_0_output > Sobel_3 size:= 9856*char
char *const explode_Split_0_output__Sobe__4 = (char*) (Shared+25344);  // explode_Split_0_output > Sobel_4 size:= 9856*char
char *const explode_Split_0_output__Sobe__5 = (char*) (Shared+31680);  // explode_Split_0_output > Sobel_5 size:= 9856*char
char *const explode_Split_0_output__Sobe__6 = (char*) (Shared+38016);  // explode_Split_0_output > Sobel_6 size:= 9856*char
char *const explode_Split_0_output__Sobe__7 = (char*) (Shared+44352);  // explode_Split_0_output > Sobel_7 size:= 9856*char
char *const explode_Split_0_output__Sobe__8 = (char*) (Shared+50688);  // explode_Split_0_output > Sobel_8 size:= 9856*char
char *const explode_Split_0_output__Sobe__9 = (char*) (Shared+57024);  // explode_Split_0_output > Sobel_9 size:= 9856*char
char *const explode_Split_0_output__Sobe__10 = (char*) (Shared+63360);  // explode_Split_0_output > Sobel_10 size:= 9856*char
char *const explode_Split_0_output__Sobe__11 = (char*) (Shared+69696);  // explode_Split_0_output > Sobel_11 size:= 9856*char
char *const explode_Split_0_output__Sobe__12 = (char*) (Shared+76032);  // explode_Split_0_output > Sobel_12 size:= 9856*char
char *const explode_Split_0_output__Sobe__13 = (char*) (Shared+82368);  // explode_Split_0_output > Sobel_13 size:= 9856*char
char *const explode_Split_0_output__Sobe__14 = (char*) (Shared+88704);  // explode_Split_0_output > Sobel_14 size:= 9856*char
char *const explode_Split_0_output__Sobe__15 = (char*) (Shared+95040);  // explode_Split_0_output > Sobel_15 size:= 9856*char
char *const implode_display_0_y__display__0 = (char*) (Shared+104896);  // implode_display_0_y > display_0 size:= 101376*char
char *const Erosion_0__implode_display_0__0 = (char*) (Shared+104896);  // Erosion_0 > implode_display_0_y size:= 6336*char
char *const Erosion_1__implode_display_0__0 = (char*) (Shared+111232);  // Erosion_1 > implode_display_0_y size:= 6336*char
char *const Erosion_2__implode_display_0__0 = (char*) (Shared+117568);  // Erosion_2 > implode_display_0_y size:= 6336*char
char *const Erosion_3__implode_display_0__0 = (char*) (Shared+123904);  // Erosion_3 > implode_display_0_y size:= 6336*char
char *const Erosion_4__implode_display_0__0 = (char*) (Shared+130240);  // Erosion_4 > implode_display_0_y size:= 6336*char
char *const Erosion_5__implode_display_0__0 = (char*) (Shared+136576);  // Erosion_5 > implode_display_0_y size:= 6336*char
char *const Erosion_6__implode_display_0__0 = (char*) (Shared+142912);  // Erosion_6 > implode_display_0_y size:= 6336*char
char *const Erosion_7__implode_display_0__0 = (char*) (Shared+149248);  // Erosion_7 > implode_display_0_y size:= 6336*char
char *const Erosion_8__implode_display_0__0 = (char*) (Shared+155584);  // Erosion_8 > implode_display_0_y size:= 6336*char
char *const Erosion_9__implode_display_0__0 = (char*) (Shared+161920);  // Erosion_9 > implode_display_0_y size:= 6336*char
char *const Erosion_10__implode_display___0 = (char*) (Shared+168256);  // Erosion_10 > implode_display_0_y size:= 6336*char
char *const Erosion_11__implode_display___0 = (char*) (Shared+174592);  // Erosion_11 > implode_display_0_y size:= 6336*char
char *const Erosion_12__implode_display___0 = (char*) (Shared+180928);  // Erosion_12 > implode_display_0_y size:= 6336*char
char *const Erosion_13__implode_display___0 = (char*) (Shared+187264);  // Erosion_13 > implode_display_0_y size:= 6336*char
char *const Erosion_14__implode_display___0 = (char*) (Shared+193600);  // Erosion_14 > implode_display_0_y size:= 6336*char
char *const Erosion_15__implode_display___0 = (char*) (Shared+199936);  // Erosion_15 > implode_display_0_y size:= 6336*char
uchar *const u__u__0 = (uchar*) (Core0+0);  // Read_YUV_0_u > display_0_u size:= 25344*uchar
uchar *const v__v__0 = (uchar*) (Core0+25344);  // Read_YUV_0_v > display_0_v size:= 25344*uchar
uchar *const output__input__0 = (uchar*) (Core0+50688);  // Sobel_0_output > Dilation_0_input size:= 9152*uchar
uchar *const output__input__1 = (uchar*) (Core0+59840);  // Dilation_0_output > Erosion_0_input size:= 7744*uchar
uchar *const y__input__0 = (uchar*) (Shared+1760);  // Read_YUV_0_y > Split_0_input size:= 101376*uchar
uchar *const output_0__input__0 = (uchar*) (Shared+0);  // explode_Split_0_output_output_0 > Sobel_0_input size:= 9856*uchar
uchar *const output_1__input__0 = (uchar*) (Shared+6336);  // explode_Split_0_output_output_1 > Sobel_1_input size:= 9856*uchar
uchar *const output_2__input__0 = (uchar*) (Shared+12672);  // explode_Split_0_output_output_2 > Sobel_2_input size:= 9856*uchar
uchar *const output_3__input__0 = (uchar*) (Shared+19008);  // explode_Split_0_output_output_3 > Sobel_3_input size:= 9856*uchar
uchar *const output_4__input__0 = (uchar*) (Shared+25344);  // explode_Split_0_output_output_4 > Sobel_4_input size:= 9856*uchar
uchar *const output_5__input__0 = (uchar*) (Shared+31680);  // explode_Split_0_output_output_5 > Sobel_5_input size:= 9856*uchar
uchar *const output_6__input__0 = (uchar*) (Shared+38016);  // explode_Split_0_output_output_6 > Sobel_6_input size:= 9856*uchar
uchar *const output_7__input__0 = (uchar*) (Shared+44352);  // explode_Split_0_output_output_7 > Sobel_7_input size:= 9856*uchar
uchar *const output_8__input__0 = (uchar*) (Shared+50688);  // explode_Split_0_output_output_8 > Sobel_8_input size:= 9856*uchar
uchar *const output_9__input__0 = (uchar*) (Shared+57024);  // explode_Split_0_output_output_9 > Sobel_9_input size:= 9856*uchar
uchar *const output_10__input__0 = (uchar*) (Shared+63360);  // explode_Split_0_output_output_10 > Sobel_10_input size:= 9856*uchar
uchar *const output_11__input__0 = (uchar*) (Shared+69696);  // explode_Split_0_output_output_11 > Sobel_11_input size:= 9856*uchar
uchar *const output_12__input__0 = (uchar*) (Shared+76032);  // explode_Split_0_output_output_12 > Sobel_12_input size:= 9856*uchar
uchar *const output_13__input__0 = (uchar*) (Shared+82368);  // explode_Split_0_output_output_13 > Sobel_13_input size:= 9856*uchar
uchar *const output_14__input__0 = (uchar*) (Shared+88704);  // explode_Split_0_output_output_14 > Sobel_14_input size:= 9856*uchar
uchar *const output_15__input__0 = (uchar*) (Shared+95040);  // explode_Split_0_output_output_15 > Sobel_15_input size:= 9856*uchar
uchar *const output__y__0 = (uchar*) (Shared+104896);  // implode_display_0_y_output > display_0_y size:= 101376*uchar
uchar *const output__y_0__0 = (uchar*) (Shared+104896);  // Erosion_0_output > implode_display_0_y_y_0 size:= 6336*uchar
uchar *const output__y_1__0 = (uchar*) (Shared+111232);  // Erosion_1_output > implode_display_0_y_y_1 size:= 6336*uchar
uchar *const output__y_2__0 = (uchar*) (Shared+117568);  // Erosion_2_output > implode_display_0_y_y_2 size:= 6336*uchar
uchar *const output__y_3__0 = (uchar*) (Shared+123904);  // Erosion_3_output > implode_display_0_y_y_3 size:= 6336*uchar
uchar *const output__y_4__0 = (uchar*) (Shared+130240);  // Erosion_4_output > implode_display_0_y_y_4 size:= 6336*uchar
uchar *const output__y_5__0 = (uchar*) (Shared+136576);  // Erosion_5_output > implode_display_0_y_y_5 size:= 6336*uchar
uchar *const output__y_6__0 = (uchar*) (Shared+142912);  // Erosion_6_output > implode_display_0_y_y_6 size:= 6336*uchar
uchar *const output__y_7__0 = (uchar*) (Shared+149248);  // Erosion_7_output > implode_display_0_y_y_7 size:= 6336*uchar
uchar *const output__y_8__0 = (uchar*) (Shared+155584);  // Erosion_8_output > implode_display_0_y_y_8 size:= 6336*uchar
uchar *const output__y_9__0 = (uchar*) (Shared+161920);  // Erosion_9_output > implode_display_0_y_y_9 size:= 6336*uchar
uchar *const output__y_10__0 = (uchar*) (Shared+168256);  // Erosion_10_output > implode_display_0_y_y_10 size:= 6336*uchar
uchar *const output__y_11__0 = (uchar*) (Shared+174592);  // Erosion_11_output > implode_display_0_y_y_11 size:= 6336*uchar
uchar *const output__y_12__0 = (uchar*) (Shared+180928);  // Erosion_12_output > implode_display_0_y_y_12 size:= 6336*uchar
uchar *const output__y_13__0 = (uchar*) (Shared+187264);  // Erosion_13_output > implode_display_0_y_y_13 size:= 6336*uchar
uchar *const output__y_14__0 = (uchar*) (Shared+193600);  // Erosion_14_output > implode_display_0_y_y_14 size:= 6336*uchar
uchar *const output__y_15__0 = (uchar*) (Shared+199936);  // Erosion_15_output > implode_display_0_y_y_15 size:= 6336*uchar
uint64_t dumpedTimes[189]; //  size:= 189*uint64_t
int nbExec[189]; //  size:= 189*int
int idx;

void *computationThread_Core0(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Initialisation(s)
	initReadYUV(352/*width*/,288/*height*/); // Read_YUV_0
	yuvDisplayInit(0/*id*/,352/*width*/,288/*height*/); // display_0
	initNbExec(nbExec,189/*nbDump*/); // 

	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(0/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+1); idx++){
			readYUV(352/*width*/,288/*height*/,y__input__0,u__u__0,v__v__0); // Read_YUV_0
		}
		dumpTime(1/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+2); idx++){
			split(16/*nbSlice*/,352/*width*/,288/*height*/,5/*overlap*/,y__input__0,NULL); // Split_0
		}
		dumpTime(2/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+3); idx++){
			// Fork explode_Split_0_output
			{
			}
		}
		dumpTime(3/*globalID*/,dumpedTimes); // 
		*(nbExec+4) = 0;
		sendStart(0, 1); // Core0 > Core1: explode_Split_0_output__Sobe__1
		dumpTime(4/*globalID*/,dumpedTimes); // 
		*(nbExec+5) = 0;
		sendEnd(); // Core0 > Core1: explode_Split_0_output__Sobe__1
		dumpTime(5/*globalID*/,dumpedTimes); // 
		*(nbExec+6) = 0;
		sendStart(0, 10); // Core0 > Core10: explode_Split_0_output__Sobe__2
		dumpTime(6/*globalID*/,dumpedTimes); // 
		*(nbExec+7) = 0;
		sendEnd(); // Core0 > Core10: explode_Split_0_output__Sobe__2
		dumpTime(7/*globalID*/,dumpedTimes); // 
		*(nbExec+8) = 0;
		sendStart(0, 11); // Core0 > Core11: explode_Split_0_output__Sobe__3
		dumpTime(8/*globalID*/,dumpedTimes); // 
		*(nbExec+9) = 0;
		sendEnd(); // Core0 > Core11: explode_Split_0_output__Sobe__3
		dumpTime(9/*globalID*/,dumpedTimes); // 
		*(nbExec+10) = 0;
		sendStart(0, 12); // Core0 > Core12: explode_Split_0_output__Sobe__4
		dumpTime(10/*globalID*/,dumpedTimes); // 
		*(nbExec+11) = 0;
		sendEnd(); // Core0 > Core12: explode_Split_0_output__Sobe__4
		dumpTime(11/*globalID*/,dumpedTimes); // 
		*(nbExec+12) = 0;
		sendStart(0, 13); // Core0 > Core13: explode_Split_0_output__Sobe__5
		dumpTime(12/*globalID*/,dumpedTimes); // 
		*(nbExec+13) = 0;
		sendEnd(); // Core0 > Core13: explode_Split_0_output__Sobe__5
		dumpTime(13/*globalID*/,dumpedTimes); // 
		*(nbExec+14) = 0;
		sendStart(0, 14); // Core0 > Core14: explode_Split_0_output__Sobe__6
		dumpTime(14/*globalID*/,dumpedTimes); // 
		*(nbExec+15) = 0;
		sendEnd(); // Core0 > Core14: explode_Split_0_output__Sobe__6
		dumpTime(15/*globalID*/,dumpedTimes); // 
		*(nbExec+16) = 0;
		sendStart(0, 15); // Core0 > Core15: explode_Split_0_output__Sobe__7
		dumpTime(16/*globalID*/,dumpedTimes); // 
		*(nbExec+17) = 0;
		sendEnd(); // Core0 > Core15: explode_Split_0_output__Sobe__7
		dumpTime(17/*globalID*/,dumpedTimes); // 
		*(nbExec+18) = 0;
		sendStart(0, 2); // Core0 > Core2: explode_Split_0_output__Sobe__8
		dumpTime(18/*globalID*/,dumpedTimes); // 
		*(nbExec+19) = 0;
		sendEnd(); // Core0 > Core2: explode_Split_0_output__Sobe__8
		dumpTime(19/*globalID*/,dumpedTimes); // 
		*(nbExec+20) = 0;
		sendStart(0, 3); // Core0 > Core3: explode_Split_0_output__Sobe__9
		dumpTime(20/*globalID*/,dumpedTimes); // 
		*(nbExec+21) = 0;
		sendEnd(); // Core0 > Core3: explode_Split_0_output__Sobe__9
		dumpTime(21/*globalID*/,dumpedTimes); // 
		*(nbExec+22) = 0;
		sendStart(0, 4); // Core0 > Core4: explode_Split_0_output__Sobe__10
		dumpTime(22/*globalID*/,dumpedTimes); // 
		*(nbExec+23) = 0;
		sendEnd(); // Core0 > Core4: explode_Split_0_output__Sobe__10
		dumpTime(23/*globalID*/,dumpedTimes); // 
		*(nbExec+24) = 0;
		sendStart(0, 5); // Core0 > Core5: explode_Split_0_output__Sobe__11
		dumpTime(24/*globalID*/,dumpedTimes); // 
		*(nbExec+25) = 0;
		sendEnd(); // Core0 > Core5: explode_Split_0_output__Sobe__11
		dumpTime(25/*globalID*/,dumpedTimes); // 
		*(nbExec+26) = 0;
		sendStart(0, 6); // Core0 > Core6: explode_Split_0_output__Sobe__12
		dumpTime(26/*globalID*/,dumpedTimes); // 
		*(nbExec+27) = 0;
		sendEnd(); // Core0 > Core6: explode_Split_0_output__Sobe__12
		dumpTime(27/*globalID*/,dumpedTimes); // 
		*(nbExec+28) = 0;
		sendStart(0, 7); // Core0 > Core7: explode_Split_0_output__Sobe__13
		dumpTime(28/*globalID*/,dumpedTimes); // 
		*(nbExec+29) = 0;
		sendEnd(); // Core0 > Core7: explode_Split_0_output__Sobe__13
		dumpTime(29/*globalID*/,dumpedTimes); // 
		*(nbExec+30) = 0;
		sendStart(0, 8); // Core0 > Core8: explode_Split_0_output__Sobe__14
		dumpTime(30/*globalID*/,dumpedTimes); // 
		*(nbExec+31) = 0;
		sendEnd(); // Core0 > Core8: explode_Split_0_output__Sobe__14
		dumpTime(31/*globalID*/,dumpedTimes); // 
		*(nbExec+32) = 0;
		sendStart(0, 9); // Core0 > Core9: explode_Split_0_output__Sobe__15
		dumpTime(32/*globalID*/,dumpedTimes); // 
		*(nbExec+33) = 0;
		sendEnd(); // Core0 > Core9: explode_Split_0_output__Sobe__15
		dumpTime(33/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+34); idx++){
			sobel(352/*width*/,28/*height*/,output_0__input__0,output__input__0); // Sobel_0
		}
		dumpTime(34/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+35); idx++){
			dilation(26/*height*/,352/*width*/,2/*window*/,output__input__0,output__input__1); // Dilation_0
		}
		dumpTime(35/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+36); idx++){
			erosion(22/*height*/,352/*width*/,2/*window*/,output__input__1,output__y_0__0); // Erosion_0
		}
		dumpTime(36/*globalID*/,dumpedTimes); // 
		*(nbExec+37) = 0;
		receiveStart(); // Core1 > Core0: Erosion_1__implode_display_0__0
		dumpTime(37/*globalID*/,dumpedTimes); // 
		*(nbExec+38) = 0;
		receiveEnd(1, 0); // Core1 > Core0: Erosion_1__implode_display_0__0
		dumpTime(38/*globalID*/,dumpedTimes); // 
		*(nbExec+39) = 0;
		receiveStart(); // Core4 > Core0: Erosion_10__implode_display___0
		dumpTime(39/*globalID*/,dumpedTimes); // 
		*(nbExec+40) = 0;
		receiveEnd(4, 0); // Core4 > Core0: Erosion_10__implode_display___0
		dumpTime(40/*globalID*/,dumpedTimes); // 
		*(nbExec+41) = 0;
		receiveStart(); // Core5 > Core0: Erosion_11__implode_display___0
		dumpTime(41/*globalID*/,dumpedTimes); // 
		*(nbExec+42) = 0;
		receiveEnd(5, 0); // Core5 > Core0: Erosion_11__implode_display___0
		dumpTime(42/*globalID*/,dumpedTimes); // 
		*(nbExec+43) = 0;
		receiveStart(); // Core6 > Core0: Erosion_12__implode_display___0
		dumpTime(43/*globalID*/,dumpedTimes); // 
		*(nbExec+44) = 0;
		receiveEnd(6, 0); // Core6 > Core0: Erosion_12__implode_display___0
		dumpTime(44/*globalID*/,dumpedTimes); // 
		*(nbExec+45) = 0;
		receiveStart(); // Core7 > Core0: Erosion_13__implode_display___0
		dumpTime(45/*globalID*/,dumpedTimes); // 
		*(nbExec+46) = 0;
		receiveEnd(7, 0); // Core7 > Core0: Erosion_13__implode_display___0
		dumpTime(46/*globalID*/,dumpedTimes); // 
		*(nbExec+47) = 0;
		receiveStart(); // Core8 > Core0: Erosion_14__implode_display___0
		dumpTime(47/*globalID*/,dumpedTimes); // 
		*(nbExec+48) = 0;
		receiveEnd(8, 0); // Core8 > Core0: Erosion_14__implode_display___0
		dumpTime(48/*globalID*/,dumpedTimes); // 
		*(nbExec+49) = 0;
		receiveStart(); // Core9 > Core0: Erosion_15__implode_display___0
		dumpTime(49/*globalID*/,dumpedTimes); // 
		*(nbExec+50) = 0;
		receiveEnd(9, 0); // Core9 > Core0: Erosion_15__implode_display___0
		dumpTime(50/*globalID*/,dumpedTimes); // 
		*(nbExec+51) = 0;
		receiveStart(); // Core10 > Core0: Erosion_2__implode_display_0__0
		dumpTime(51/*globalID*/,dumpedTimes); // 
		*(nbExec+52) = 0;
		receiveEnd(10, 0); // Core10 > Core0: Erosion_2__implode_display_0__0
		dumpTime(52/*globalID*/,dumpedTimes); // 
		*(nbExec+53) = 0;
		receiveStart(); // Core11 > Core0: Erosion_3__implode_display_0__0
		dumpTime(53/*globalID*/,dumpedTimes); // 
		*(nbExec+54) = 0;
		receiveEnd(11, 0); // Core11 > Core0: Erosion_3__implode_display_0__0
		dumpTime(54/*globalID*/,dumpedTimes); // 
		*(nbExec+55) = 0;
		receiveStart(); // Core12 > Core0: Erosion_4__implode_display_0__0
		dumpTime(55/*globalID*/,dumpedTimes); // 
		*(nbExec+56) = 0;
		receiveEnd(12, 0); // Core12 > Core0: Erosion_4__implode_display_0__0
		dumpTime(56/*globalID*/,dumpedTimes); // 
		*(nbExec+57) = 0;
		receiveStart(); // Core13 > Core0: Erosion_5__implode_display_0__0
		dumpTime(57/*globalID*/,dumpedTimes); // 
		*(nbExec+58) = 0;
		receiveEnd(13, 0); // Core13 > Core0: Erosion_5__implode_display_0__0
		dumpTime(58/*globalID*/,dumpedTimes); // 
		*(nbExec+59) = 0;
		receiveStart(); // Core14 > Core0: Erosion_6__implode_display_0__0
		dumpTime(59/*globalID*/,dumpedTimes); // 
		*(nbExec+60) = 0;
		receiveEnd(14, 0); // Core14 > Core0: Erosion_6__implode_display_0__0
		dumpTime(60/*globalID*/,dumpedTimes); // 
		*(nbExec+61) = 0;
		receiveStart(); // Core15 > Core0: Erosion_7__implode_display_0__0
		dumpTime(61/*globalID*/,dumpedTimes); // 
		*(nbExec+62) = 0;
		receiveEnd(15, 0); // Core15 > Core0: Erosion_7__implode_display_0__0
		dumpTime(62/*globalID*/,dumpedTimes); // 
		*(nbExec+63) = 0;
		receiveStart(); // Core2 > Core0: Erosion_8__implode_display_0__0
		dumpTime(63/*globalID*/,dumpedTimes); // 
		*(nbExec+64) = 0;
		receiveEnd(2, 0); // Core2 > Core0: Erosion_8__implode_display_0__0
		dumpTime(64/*globalID*/,dumpedTimes); // 
		*(nbExec+65) = 0;
		receiveStart(); // Core3 > Core0: Erosion_9__implode_display_0__0
		dumpTime(65/*globalID*/,dumpedTimes); // 
		*(nbExec+66) = 0;
		receiveEnd(3, 0); // Core3 > Core0: Erosion_9__implode_display_0__0
		dumpTime(66/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+67); idx++){
			// Join implode_display_0_y
			{
			}
		}
		dumpTime(67/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+68); idx++){
			yuvDisplay(0/*id*/,output__y__0,u__u__0,v__v__0); // display_0
		}
		dumpTime(68/*globalID*/,dumpedTimes); // 
		pthread_barrier_wait(&iter_barrier);
		writeTime(dumpedTimes,189/*nbDump*/, nbExec);
	}
	return NULL;
}

