/**
 * @file Core15.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:00:00 CET 2021
 *
 * Code generated for processing element Core15 (ID=15).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__7;  // explode_Split_0_output > Sobel_7 size:= 9856*char defined in Core0
extern uchar *const output_7__input__0;  // explode_Split_0_output_output_7 > Sobel_7_input size:= 9856*uchar defined in Core0
extern uchar *const output__y_7__0;  // Erosion_7_output > implode_display_0_y_y_7 size:= 6336*uchar defined in Core0
extern char *const Erosion_7__implode_display_0__0;  // Erosion_7 > implode_display_0_y size:= 6336*char defined in Core0
extern uint64_t dumpedTimes[189]; //  size:= 189*uint64_t
extern int nbExec[189]; //  size:= 189*int

// Core Global Definitions
char Core15[16896]; //  size:= 16896*char
char *const Sobel_7__Dilation_7__0 = (char*) (Core15+0);  // Sobel_7 > Dilation_7 size:= 9152*char
char *const Dilation_7__Erosion_7__0 = (char*) (Core15+9152);  // Dilation_7 > Erosion_7 size:= 7744*char
uchar *const output__input__14 = (uchar*) (Core15+0);  // Sobel_7_output > Dilation_7_input size:= 9152*uchar
uchar *const output__input__15 = (uchar*) (Core15+9152);  // Dilation_7_output > Erosion_7_input size:= 7744*uchar
int idx;

void *computationThread_Core15(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(181/*globalID*/,dumpedTimes); // 
		*(nbExec+182) = 0;
		receiveStart(); // Core0 > Core15: explode_Split_0_output__Sobe__7
		dumpTime(182/*globalID*/,dumpedTimes); // 
		*(nbExec+183) = 0;
		receiveEnd(0, 15); // Core0 > Core15: explode_Split_0_output__Sobe__7
		dumpTime(183/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+184); idx++){
			sobel(352/*width*/,28/*height*/,output_7__input__0,output__input__14); // Sobel_7
		}
		dumpTime(184/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+185); idx++){
			dilation(26/*height*/,352/*width*/,2/*window*/,output__input__14,output__input__15); // Dilation_7
		}
		dumpTime(185/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+186); idx++){
			erosion(22/*height*/,352/*width*/,2/*window*/,output__input__15,output__y_7__0); // Erosion_7
		}
		dumpTime(186/*globalID*/,dumpedTimes); // 
		*(nbExec+187) = 0;
		sendStart(15, 0); // Core15 > Core0: Erosion_7__implode_display_0__0
		dumpTime(187/*globalID*/,dumpedTimes); // 
		*(nbExec+188) = 0;
		sendEnd(); // Core15 > Core0: Erosion_7__implode_display_0__0
		dumpTime(188/*globalID*/,dumpedTimes); // 
		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

