/**
 * @file Core7.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:00:00 CET 2021
 *
 * Code generated for processing element Core7 (ID=7).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__13;  // explode_Split_0_output > Sobel_13 size:= 9856*char defined in Core0
extern uchar *const output_13__input__0;  // explode_Split_0_output_output_13 > Sobel_13_input size:= 9856*uchar defined in Core0
extern uchar *const output__y_13__0;  // Erosion_13_output > implode_display_0_y_y_13 size:= 6336*uchar defined in Core0
extern char *const Erosion_13__implode_display___0;  // Erosion_13 > implode_display_0_y size:= 6336*char defined in Core0
extern uint64_t dumpedTimes[189]; //  size:= 189*uint64_t
extern int nbExec[189]; //  size:= 189*int

// Core Global Definitions
char Core7[16896]; //  size:= 16896*char
char *const Sobel_13__Dilation_13__0 = (char*) (Core7+0);  // Sobel_13 > Dilation_13 size:= 9152*char
char *const Dilation_13__Erosion_13__0 = (char*) (Core7+9152);  // Dilation_13 > Erosion_13 size:= 7744*char
uchar *const output__input__26 = (uchar*) (Core7+0);  // Sobel_13_output > Dilation_13_input size:= 9152*uchar
uchar *const output__input__27 = (uchar*) (Core7+9152);  // Dilation_13_output > Erosion_13_input size:= 7744*uchar
int idx;

void *computationThread_Core7(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(117/*globalID*/,dumpedTimes); // 
		*(nbExec+118) = 0;
		receiveStart(); // Core0 > Core7: explode_Split_0_output__Sobe__13
		dumpTime(118/*globalID*/,dumpedTimes); // 
		*(nbExec+119) = 0;
		receiveEnd(0, 7); // Core0 > Core7: explode_Split_0_output__Sobe__13
		dumpTime(119/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+120); idx++){
			sobel(352/*width*/,28/*height*/,output_13__input__0,output__input__26); // Sobel_13
		}
		dumpTime(120/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+121); idx++){
			dilation(26/*height*/,352/*width*/,2/*window*/,output__input__26,output__input__27); // Dilation_13
		}
		dumpTime(121/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+122); idx++){
			erosion(22/*height*/,352/*width*/,2/*window*/,output__input__27,output__y_13__0); // Erosion_13
		}
		dumpTime(122/*globalID*/,dumpedTimes); // 
		*(nbExec+123) = 0;
		sendStart(7, 0); // Core7 > Core0: Erosion_13__implode_display___0
		dumpTime(123/*globalID*/,dumpedTimes); // 
		*(nbExec+124) = 0;
		sendEnd(); // Core7 > Core0: Erosion_13__implode_display___0
		dumpTime(124/*globalID*/,dumpedTimes); // 
		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

