/**
 * @file Core5.c
 * @generated by InstrumentedCPrinter
 * @date Thu Mar 18 19:00:00 CET 2021
 *
 * Code generated for processing element Core5 (ID=5).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int stopThreads;
extern char *const explode_Split_0_output__Sobe__11;  // explode_Split_0_output > Sobel_11 size:= 9856*char defined in Core0
extern uchar *const output_11__input__0;  // explode_Split_0_output_output_11 > Sobel_11_input size:= 9856*uchar defined in Core0
extern uchar *const output__y_11__0;  // Erosion_11_output > implode_display_0_y_y_11 size:= 6336*uchar defined in Core0
extern char *const Erosion_11__implode_display___0;  // Erosion_11 > implode_display_0_y size:= 6336*char defined in Core0
extern uint64_t dumpedTimes[189]; //  size:= 189*uint64_t
extern int nbExec[189]; //  size:= 189*int

// Core Global Definitions
char Core5[16896]; //  size:= 16896*char
char *const Sobel_11__Dilation_11__0 = (char*) (Core5+0);  // Sobel_11 > Dilation_11 size:= 9152*char
char *const Dilation_11__Erosion_11__0 = (char*) (Core5+9152);  // Dilation_11 > Erosion_11 size:= 7744*char
uchar *const output__input__22 = (uchar*) (Core5+0);  // Sobel_11_output > Dilation_11_input size:= 9152*uchar
uchar *const output__input__23 = (uchar*) (Core5+9152);  // Dilation_11_output > Erosion_11_input size:= 7744*uchar
int idx;

void *computationThread_Core5(void *arg){
	if (arg != NULL) {
		printf("Warning: expecting NULL arguments\n");
	}
	// Begin the execution loop
#ifdef LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<LOOP_SIZE;index++){
#else // Default case of an infinite loop
	while(1){
#endif
		pthread_barrier_wait(&iter_barrier);
		if(stopThreads){
			pthread_exit(NULL);
		}
		dumpTime(101/*globalID*/,dumpedTimes); // 
		*(nbExec+102) = 0;
		receiveStart(); // Core0 > Core5: explode_Split_0_output__Sobe__11
		dumpTime(102/*globalID*/,dumpedTimes); // 
		*(nbExec+103) = 0;
		receiveEnd(0, 5); // Core0 > Core5: explode_Split_0_output__Sobe__11
		dumpTime(103/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+104); idx++){
			sobel(352/*width*/,28/*height*/,output_11__input__0,output__input__22); // Sobel_11
		}
		dumpTime(104/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+105); idx++){
			dilation(26/*height*/,352/*width*/,2/*window*/,output__input__22,output__input__23); // Dilation_11
		}
		dumpTime(105/*globalID*/,dumpedTimes); // 
		for(idx=0; idx<*(nbExec+106); idx++){
			erosion(22/*height*/,352/*width*/,2/*window*/,output__input__23,output__y_11__0); // Erosion_11
		}
		dumpTime(106/*globalID*/,dumpedTimes); // 
		*(nbExec+107) = 0;
		sendStart(5, 0); // Core5 > Core0: Erosion_11__implode_display___0
		dumpTime(107/*globalID*/,dumpedTimes); // 
		*(nbExec+108) = 0;
		sendEnd(); // Core5 > Core0: Erosion_11__implode_display___0
		dumpTime(108/*globalID*/,dumpedTimes); // 
		pthread_barrier_wait(&iter_barrier);
	}
	return NULL;
}

